#!/usr/bin/env bash

# MUST: Process substitution are not allowed.  Older container
# technologies prior to docker breaks process substitutions inside
# them.

# MUST: Support older bash versions.  No fancy features other than
# basic list manipulations.

# TODO: un pretty printer

# TODO: rendre chaque commandes externes testable pour des failures en
# passant par une commande intermédire qui compare un id fourni pour
# savoir si on doit provoquer le non-happy path.

# TODO: améliorer l'anglais dans le message d'aide.


help() {
	cat <<"HELP";
NAME

	rrssh - remote recursive ssh

SYNOPSIS

	rrssh [<options>...] <main-command> [--- <rrssh commands>...]

DESCRIPTION

	An automation tool that uses ssh to jump through any number of
	hosts to run commands and transfer files and directories.  Its
	commands are a basic shell-like scripting language provided in
	arguments or in a file.  Execution of the script and file
	transfers will span as many hosts as indicated.  A strong panic
	mecanism will stop the execution at any unexpected failures,
	either external commands exiting with an unhandled non-0 code or
	an internal rrssh failure.

	Rrssh is a bash script that implements a recursive scripting
	language.  Rrssh is, in most part, a bash "kernel" that duplicates
	itself locally or through an ssh connection.  Because of its
	nature, rrssh has an extensive test suite to ensure its
	reliability.

	The only requirements for the target hosts are an old bash version
	and basic utilities.

MAIN COMMANDS

	For the main commands that need a script, the script must be
	provided either with the option --- or -f.

	run

		Run the script.

	check

		Examine the script for syntax errors and other problems
		without running it.

	print [-n <index>] [-lt]

		Prints the script, one token per line.  With -n, only print
		that token.  Tokens are indexed at 0.  With -t, only print the
		amount of tokens.  With -l, do not quote the tokens using
		printf %q.

	print-kernel

		Duplicates the kernel to stdout.  Send it to shellcheck for
		analysis.

OPTIONS

	-h, --help

		Show this help message.

	--- <commands>...

		Stop reading options and arguments.  The remaining arguments
		will be interpreted as a script.  --- is necessary if the
		script is provided by arguments.

	-f, --file <filepath>

		Provide a file of commands to execute instead of reading from
		the arguments.  If file is "-", then read from stdin.

	-p

		Make any command chain that does not exit with 0 trigger a
		rrssh panic.  Default behavior is to only make the parent
		scope exit non-0.

	-i

		Any command host or su that fails will be handled as if their
		internal scope had exited non-0 instead of triggering a panic.

	-n <index>

		Read the description of the command "print".

	-l, -t

		Read the description of the command "print".

EXECUTION

	A rrssh script is usually made of scopes [ ].  Unlike normal
	shells, by default, any command "chain" that exits non-0 will stop
	further execution of the scope and the scope will exit with non-0.
	The -p option will make rrssh panic instead.  By default, any host
	or su command that fails will trigger a panic unless the option -i
	is used.  With -i, a failing host or su command will behave as if
	its inner scope exited non-0.

COMMANDS

	host <destination> [ <commands>... ]
	sudo-host <destination> [ <commands>... ]

		These commands are the main purpose of using rrssh.
		Duplicates the kernel through a single ssh connection and
		execute the sub commands on the remote host.  This command can
		include itself arbitrarily many times to reach any depth.  The
		[ ] variants are scoped.  The : variants takes all the
		commands until the end of the current scope.  The sudo
		variants will run the actual ssh command through sudo.

	su <user> [ <commands>... ]
	sudo-su <user> [ <commands>... ]

		TODO

	[ <commands>... ]

		TODO

	command <system-command>
	command [ <argv>... ]
	--- <argv>... ---

		TODO

	true
	false

		Do nothing, with success or failure.

	print <text>

		TODO

	cd <path>
	home
	pushd <path>
	popd

		Change your current directory.

	pwd

		Print the current working directory.

	take-file <path> <new-name> <dropdir>
	take-dir <path> <new-name> <dropdir>

		Bring a file or directory to a drop directory on the current
		host, a parent host, or a future child host.  You can provide
		a new name for the file or directory.  You can preserve the
		current name by providing an empty argument as the name ("").

	drop-dir <name> <path>

		Indicate a drop directory (and its name) to receive files and
		directories taken with take-file or take-dir.  The directory
		must already be created.

OPERATORS

	TODO

OPTIONS USED BY RRSSH'S TEST SUITE

	--make-command-fail <id>

		Do not use this.  This is intended for the test suite.  Makes
		a command fail to validate the behavior of the error paths.

	--fake-su

		Do not use this.  This is intended for the test suite.  Make
		the su commands not really attempt to switch user to prevent
		passwords from breaking the test suite.

COMMANDS USED BY RRSSH'S TEST SUITE

	make-command-fail <id>

		Do not use this.  This is intended for the test suite.  Makes
		a command fail to validate the behavior of the error paths.
		This will be in effect only for the current scope and all
		child scopes.

EXAMPLES

	TODO

PROBLEMS

	TODO

HELP
}

unimplemented_wishlist() {
	cat <<"HELP";


	pretty-print

		Pretty prints the script for an easier visual analysis.

	walk

		Try going through all the hosts and all the user switchings,
		without running any commands.




	for <variable> in <values>... [ <commands>... ]
	for <variable> <delim> <values>... <delim> <command>
	for <variable> <delim> <values>... <delim> [ <commands>... ]
	for <variable> --- <values>... --- <command>
	for <variable> --- <values>... --- [ <commands>... ]

		Loop a block of code over some values.  Each time, all
		instances of <variable> in the commands will be substituted.
		Use special symbols to avoid replacing unwanted parts of the
		commands.  You cannot replace syntax elements of the language
		with variables.

	var <variable> <value>

		Create a variable.  The variable is available and affectable
		in the current scope and all child scopes.  You cannot create
		a variable if its name already exists in the current scope.
		Use the hosts' "test" command with rrssh's "command" command
		to compare its value.

	set-var <variable> <value>

		Change the value of a variable.  The variable must have
		previously been created with the var command in the current
		scope or a parent scope.

	if <command> then <command>
			[ elif <command> then <command> ]...
			[ else <command> then <command> ]
			fi

		TODO



pour implémenter les if et les scopes, il faut donner au nouveau
kernel le token qui met fin à son scope (pour les scope) et une option
qui indique qu'il doit rouler une seule commande (pour les if).


HELP
}


opt_file=0;
arg_file="";

opt_n=0;
arg_n="";

opt_l=0;
opt_t=0;
opt_p=0;
opt_i=0;
opt_fake_su=0;

opt_script_provided=0;
arg_script=();

make_command_fail_ids=();

trailing_args=();
while (($#)); do
	arg=$1;
	shift;
	case "$arg" in
		(-h|--help)
			help;
			exit 0;
			;;
		(---)
			opt_script_provided=1;
			arg_script=("$@");
			set --;
			break;
			;;
		(-f|--file)
			opt_file=1;
			arg_file=$1;
			shift;
			;;
		(-n)
			opt_n=1;
			arg_n=$1;
			[[ "$arg_n" =~ ^[0-9]+$ ]] || {
				1>&2 echo "The value provided to -n must be numeric and positive.";
				exit 1;
			};
			shift;
		    ;;
		(-l)
			opt_l=1;
			;;
		(-t)
			opt_t=1;
			;;
		(-p)
			opt_p=1;
			;;
		(-i)
			opt_i=1;
			;;
		(--fake-su)
			opt_fake_su=1;
			;;
		(--make-command-fail)
			make_command_fail_ids+=("$1");
			shift;
			;;
		(*)
			trailing_args+=("$arg");
			;;
	esac
done;
set -- "${trailing_args[@]}" "$@";
unset trailing_args;
unset arg;


testable() {
	local command_id=$1;
	shift;
    local id;
	for id in "${make_command_fail_ids[@]}"; do
		if [ "$id" == "$command_id" ]; then
			return 1;
		fi;
	done;
	"$@";
}





dump_bin() {
	echo %binary_object;
	# TODO: i probably have to send useless chars and read them back
	# because base64 doesn't seem to handle an actual empty stream.
	base64;
	echo %end;
}
read_line() {
	local IFS="";
	local line;
	read -r line;
	printf %s "$line";
}
read_line_ln() {
	printf '%s\n' "$(read_line)";
}
read_bin() {
	local first_line=$(read_line);
	[ "$first_line" == %binary_object ] || return 1;
	{
		while IFS="" read -r line || [ -n "$line" ]; do
			[ "$line" == %end ] && break;
			printf %s "$line";
		done;
	} | base64 --decode;
}


print_kernel() {
	cat <<"KERNEL";
#!/bin/bash

# The shebang line is for shellcheck

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd);
KERNEL_PATH=$SCRIPT_DIR/${0##*/};

# stdout for communication.  stderr for accidental garbage and trying
# to raise a sigpipe.  stdout is moved to 3 to avoid accidental
# garbage from breaking the protocol.
exec 3>&1 1>&2;

KERNEL

	declare -f dump_bin;
	declare -f read_line;
	declare -f read_line_ln;
	declare -f read_bin;
	declare -f print_kernel;
	declare -f testable;

	cat <<"KERNEL";


echocom() {
	echo "$@" 1>&3;
}

echocom @kernel_start;

send_to_stdout() {
	echocom @@print_stdout;
	dump_bin 1>&3;
}
send_to_stderr() {
	echocom @@print_stderr;
	dump_bin 1>&3;
}

echoout() {
	echo "$@" | send_to_stdout;
}
printfout() {
	printf "$@" | send_to_stdout;
}

echoerr() {
	echo "$@" | send_to_stderr;
}
printferr() {
	printf "$@" | send_to_stderr;
}


# calling panic from inside a subshell will not cause rrssh to stop automatically!
panic() {
	printferr 'PANIC: %s PANIC\n' "$@";
	echocom @panic;
	exit 1;
}

error() {
	printferr 'ERROR: %s ERROR\n' "$@";
}

debug() {
	true || return 0;
	printferr 'DEBUG: %s DEBUG\n' "$@";
}




# the multiple "operation modes" of the kernel are for scanning or
# other details without having to duplicate code.

# The calling protocol of the kernel never requires the whole user
# script to be provided by arguments because it may be
# "dangerously" long (i dont know whether there is a platform with an
# argument limit) or it may contain credentials (must not show up in
# ps aux).

# The user script, files and directories to transmit, most information
# and other "object" types must be provided at the end of the kernel
# script.  Some basic information like the "operation mode" is
# provided via arguments, though.  The line "###;;;" indicates the end
# of the kernel and the beginning of the objects.  First we put all
# small-ish object, which is anything other than files and folders,
# then a separator, then we dump files and folders.  This is to avoid
# the need to skip large files/folders and thus speed up a little bit.



rrssh_id=""; # unique id for the whole runtime
rrssh_fork_depth=0;
rrssh_host_depth=0;



# operation mode
op_mode=""; # enum of: run scan

# are we the first kernel?  therefore we dont have a parent scope.
is_root_kernel=0;

# are we suposed to run only one command chain?
is_one_command_chain_limit=0;




while (($#)); do
	arg=$1;
	shift;
	case "$arg" in
		(--mode)
			op_mode=$1;
			shift;
			;;
		(--root)
			is_root_kernel=1;
			;;
		(--one-command-chain-limit)
			is_one_command_chain_limit=1;
			;;
	esac;
done;
unset arg;



# if we are not the root kernel, then this is the token that's gonna
# close our scope.
toplevel_scope_closing_token="";


toplevel_args=();
total_toplevel_args_shift_count=0;

make_command_fail_ids=();

opt_p=0;
opt_i=0;
opt_fake_su=0;

shift_toplevel_args() {
	local shift_count=${1:-1};
	set -- "${toplevel_args[@]}";
	shift "$shift_count";
	toplevel_args=("$@");
	((total_toplevel_args_shift_count += shift_count));
}
peek_toplevel_args() {
	printf %s "${toplevel_args[0]}";
}
any_toplevel_args_remaining() {
	((${#toplevel_args[@]} > 0));
}

skip_kernel() {
	local line;
	while IFS="" read -r line || [ -n "$line" ]; do
		[ "$line" == "###;;;" ] && break;
	done;
}
load_eof_values() {
	local object_type;
	{
		skip_kernel;
		while IFS="" read -r object_type || [ -n "$object_type" ]; do
			case "$object_type" in
				(@end_of_header)
					break;
					;;
				(@@toplevel_arg)
					toplevel_args+=("$(read_bin)");
					;;
				(@@toplevel_scope_closing_token)
					toplevel_scope_closing_token=$(read_bin);
					;;
				(@@rrssh_id)
					rrssh_id=$(read_bin);
					;;
				(@@rrssh_fork_depth)
					rrssh_fork_depth=$(read_bin);
					;;
				(@@rrssh_host_depth)
					rrssh_host_depth=$(read_bin);
					;;
				(@opt_p)
					opt_p=1;
					;;
				(@opt_i)
					opt_i=1;
					;;
				(@fake_su)
					opt_fake_su=1;
					;;
				(@@make_command_fail_id)
					make_command_fail_ids+=("$(read_bin)");
					;;
				(*)
					panic "Unknown object in kernel dump: '$object_type'.";
					;;
			esac;
		done;
	} < "$KERNEL_PATH";
}




# i dont trust bash hashes with user inputs.  therefore everything
# relating to files and dirs is stored is different lists of equal
# lengths at all times, where the same index in each list is a
# different property of the same object.

localhost_dropdirs_names=();
localhost_dropdirs_paths=();



begin_basic_fork() {
	print_kernel;
	echo;
	echo '###;;;';

	local token;
	for token in "${toplevel_args[@]}"; do
		echo @@toplevel_arg;
		dump_bin <<<"$token";
	done;

	local id;
	for id in "${make_command_fail_ids[@]}"; do
		echo @@make_command_fail_id;
		dump_bin <<<"$id";
	done;

	((opt_p)) && echo @opt_p;
	((opt_i)) && echo @opt_i;
	((opt_fake_su)) && echo @fake_su;

	echo @@rrssh_id;
	dump_bin <<<"$rrssh_id";
	echo @@rrssh_fork_depth;
	dump_bin <<<$((rrssh_fork_depth + 1));

}



handle_incoming_files_and_dirs() {
	local header=$1; # the @@@@ line
	local is_local=$2; # 1 = file system. 0 = stdin.
	local dest_drop_dir=$3;
	local dest_path=$4;
	local local_source_path=$5; # only provided for local source

	local temp_holder=$(mktemp);
	if ((is_local)); then
		cat -- "$local_source_path";
	else
		read_bin;
	fi > "$temp_holder";

	


	# TODO: optimize everything



	if ! ((is_root_kernel)); then
		echo "$header";
		dump_bin <<<"$dest_drop_dir";
		dump_bin <<<"$dest_path";
		dump_bin < "$temp_holder";
	fi;

	rm -f "$temp_holder";

}

handle_incoming_files_and_dirs_in_stream() {
	local line;
	while IFS="" read -r line || [ -n "$line" ]; do
		case "$line" in
			(@@@@*)
				echo "$line";
				read_bin | dump_bin;
				read_bin | dump_bin;
				read_bin | dump_bin;
				;;
			(@@@@file|@@@@dir)
				# handle_incoming_files_and_dirs "$line" 0 "$(read_bin)" "$(read_bin)";
				true;
				;;
			(@@@*)
				echo "$line";
				read_bin | dump_bin;
				read_bin | dump_bin;
				;;
			(@@*)
				echo "$line";
				read_bin | dump_bin;
				;;
			(@*)
				echo "$line";
				;;			
			(*)
				# error "handle_incoming_files_and_dirs: Unknown message '$line'.  Panic.";
				echo @panic;
				;;
		esac;
	done;
}



# in a huge pipe line of many commands that communicate with our
# protocol by sending messages to their fd 1 (next command in pipe
# line) or fd 3, we must avoid the situation where multiple sections
# of the pipe line tries to write messages to fd 3 (our parent
# kernel).  multiple writes are not atomic, therefore the protocol
# breaks because it breaks the flow of @header followed by its
# arguments if an other command begins to write a message while the
# previous message is not completed.

# the easiest way to enforce protection of the protocol is that only
# one command in a pipe line is "priviledged" to write to fd 3, the
# others must write to their fd 1 or in temp files that can be managed
# at the appropriate time.  i dont want to "automate" the handling of
# fd 3 with lock files, it's probably asking for problems or risking a
# deadlock.

# THEREFORE generic_message_handler will be that priviledged function,
# so it goes at the end of a pipe line.

generic_message_handler() {
	# we cannot handle panic because we will always be inside a
	# subshell.  therefore we must forward the panic, which is also
	# our own panic mecanism for unknown message type.

	# the number of @ in general is the number of argments plus one,
	# so that a function like this one can yield back messages that it
	# doesn't support.

	local line;
	while IFS="" read -r line || [ -n "$line" ]; do
		# debug "GENERIC $rrssh_fork_depth: $line";
		case "$line" in
			(@@print_stdout)
				read_bin | send_to_stdout;
				;;
			(@@print_stderr)
				read_bin | send_to_stderr;
				;;
			(@panic)
				echo @panic;
				;;
			(@bliss)
				echo @bliss;
				;;
			(@@exitcode)
				echocom @@exitcode;
				read_bin | dump_bin 1>&3;
				;;
			(@@@@*)
				if ! ((is_root_kernel)); then
					echocom "$line";
					read_bin | dump_bin 1>&3;
					read_bin | dump_bin 1>&3;
					read_bin | dump_bin 1>&3;
				else
					read_bin | dump_bin > /dev/null;
					read_bin | dump_bin > /dev/null;
					read_bin | dump_bin > /dev/null;
				fi;
				;;
			(@@@*)
				echo "$line";
				read_bin | dump_bin;
				read_bin | dump_bin;
				;;
			(@@*)
				echo "$line";
				read_bin | dump_bin;
				;;
			(@*)
				echo "$line";
				;;
			(*)
				error "generic_message_handler: Unknown message '$line'.  Panic.";
				echo @panic;
				;;
		esac;
	done;
}



# The "contract" with the command commands is as follow: They are
# responsible for shifting and consuming the toplevel_args because
# only they know how much arguments they consume.  They must respect
# the value of op_mode.  They can panic.  They must use their
# exit-code to indicate whether they must be considered successful or
# in error in regards to the operators and or not try.  They must only
# run (but always consume their arguments) if the main loop sets the
# variable indicating to do so.

# the main execution loop sets this when commands must read their
# arguments but skip their execution.  for example when running a
# "command chain".

skip_current_command_execution_flag=0;

current_command_must_run_p() {
	[ "$op_mode" == scan ] && return 1;
	((skip_current_command_execution_flag)) && return 1;
	return 0;
}

command_command() {
	local arg0=$(peek_toplevel_args);
	shift_toplevel_args;

	# command needs either a string for system() or [ ], so one argument obligatory.
	any_toplevel_args_remaining || {
		panic "The command 'command' must be provided with an argument.";
	};

	local arg1=$(peek_toplevel_args);
	local string_command="";
	local is_string=1;
	local argv=();
	local end_token="";

	if [ "$arg0" == --- ]; then
		is_string=0;
		end_token="---";
	else
		shift_toplevel_args;
		if [ "$arg1" == "[" ]; then
			is_string=0;
			end_token="]";
		else
			string_command=$arg1;
		fi;
	fi;
	
	local end_token_reached=0;
	if ! ((is_string)); then
		while any_toplevel_args_remaining; do
			if [ "$(peek_toplevel_args)" == "$end_token" ]; then
				end_token_reached=1;
				shift_toplevel_args;
				break;
			fi;
			argv+=("$(peek_toplevel_args)");
			shift_toplevel_args;
		done;

		((end_token_reached)) || {
			panic "The command 'command' must end with the corresponding ending token: '$end_token'.";
		};
	fi;

	current_command_must_run_p || return 0;

	local rc=0;
	if ((is_string)); then
		bash -c "$string_command" 0< /dev/null 3>&- |& send_to_stdout;
		rc=${PIPESTATUS[0]};
	else
		(
			"${argv[@]}";
			exit "$?";
		) 0< /dev/null 3>&- |& send_to_stdout;
		rc=${PIPESTATUS[0]};
	fi;
	wait;

	return "$rc";
}


command_fork() {
	local command_name=$(peek_toplevel_args);
	shift_toplevel_args;

	# TODO: if forking locally, then dont reprint all files, put a
	# reference to the first kernel on the current host.

	local is_host_command=0;
	local is_su_command=0;
	local is_scope_command=0;
	local is_sudo_prefix=0;

	case "$command_name" in
		(host)
			is_host_command=1;
			;;
		(sudo-host)
			is_host_command=1;
			is_sudo_prefix=1;
			;;
		(su)
			is_su_command=1;
			;;
		(sudo-su)
			is_su_command=1;
			is_sudo_prefix=1;
			;;
		("[")
			is_scope_command=1;
			;;
	esac;

	local arg_destination; # host commands
	local arg_username; # su commands
	if ! ((is_scope_command)); then
		arg_destination=$(peek_toplevel_args);
		arg_username=$(peek_toplevel_args);
		shift_toplevel_args;
		if ! [ "$(peek_toplevel_args)" == "[" ]; then
			panic "The '$command_name' command must begin with an opening '['";
		fi;
	    shift_toplevel_args;
	fi;

	# at this point, the opening square bracket is consumed, the next
	# toplevel arg is the first token inside the scope.  the closing
	# square bracket will come later and be consumed by the sub
	# kernel.

	# pre-execution analysis
	local total_scope_args_shift=0;
	local total_scope_args_shift_provided=0;
	local sub_analyser_bliss=0;


	local sub_analyser_kernel_path=$(mktemp);
	local analysis_output=$(mktemp);
	(
		begin_basic_fork;

		echo @@toplevel_scope_closing_token;
		dump_bin <<<"]";

		echo @@rrssh_host_depth;
		dump_bin <<<$((rrssh_host_depth + 1));

		echo @end_of_header;
	) > "$sub_analyser_kernel_path";
	bash "$sub_analyser_kernel_path" -- --mode scan | generic_message_handler > "$analysis_output";
	rm -f "$sub_analyser_kernel_path";
	local line;
	while IFS="" read -r line || [ -n "$line" ]; do
		case "$line" in
			(@@total_toplevel_shift)
				total_scope_args_shift_provided=1;
				total_scope_args_shift=$(read_bin);
				;;
			(@bliss)
				sub_analyser_bliss=1;
				;;
			(@panic)
				rm -f "$analysis_output";
				panic "Sub kernel panicked during analysis.";
				;;
			(@kernel_start)
				true;
				;;
			(*)
				rm -f "$analysis_output";
				panic "Unknown message during scope analysis: '$line'.";
				;;
		esac;
	done < "$analysis_output";
	rm -f "$analysis_output";
	((sub_analyser_bliss)) ||
		panic "Sub scope analyser did not end blissfully.";

	current_command_must_run_p || {
	    shift_toplevel_args "$total_scope_args_shift";
		return 0;
	};



	local temp_com_file=$(mktemp);
	(
		begin_basic_fork;



		echo @@toplevel_scope_closing_token;
		dump_bin <<<"]";

		echo @@rrssh_host_depth;
		dump_bin <<<$((rrssh_host_depth + 1));

		echo @end_of_header;

		# TODO: append files and folders only if we are a host
		# command.  hum, but there's no guarenty that the new user
		# can read the previous user's kernel to retrive information.

	) | (

		print_landing_script() {

			# the landing script should always exit 0 if it
			# successfully runs the kernel, so that we know from the
			# exit code whether the ssh/su command or the landing
			# failed.

			local call_args=("$@");
			cat <<LANDING_SCRIPT;
echo @landing_start;

call_args=($(printf "%q " "${call_args[@]}"));
make_command_fail_ids=($(printf "%q " "${make_command_fail_ids[@]}"));
LANDING_SCRIPT

			declare -f dump_bin;
			declare -f testable;

			cat <<"LANDING_SCRIPT";

send_to_stderr() {
	echo @@print_stderr;
	dump_bin;
}
send_to_landing_err() {
	echo @@print_landing_err;
	dump_bin;
}
printferr() {
	printf "$@" | send_to_stderr;
}
printf_landing_err() {
	printf "$@" | send_to_landing_err;
}
error() {
	printferr "ERROR: %s ERROR\n" "$@";
}
debug() {
	printferr "DEBUG: %s DEBUG\n" "$@";
}




kernel_file_path=$(testable id_nuirhienvfh mktemp) || {
	printf_landing_err "mktemp failed.  Could not create a temporary file for the sub kernel.";
	exit 1;
};

testable id_fdhv9qh5gf tee "$kernel_file_path" &> /dev/null || {
	printf_landing_err "tee failed.  Could not dump contents to the temporary file meant to hold the sub kernel."
	rm -f "$kernel_file_path";
	exit 1;
};

testable id_asudhfisuh bash "$kernel_file_path" -- "${call_args[@]}";
rm -f "$kernel_file_path";
exit 0;

LANDING_SCRIPT

		}

		cmd=();
		if ((is_sudo_prefix)); then
			cmd+=(sudo);
		fi;
		if ((is_host_command)); then
			cmd+=(ssh -o ConnectTimeout=10 -- "$arg_destination");
		elif ((is_su_command)); then
			if ! ((opt_fake_su)); then
				cmd+=(su --login -- "$arg_username" -c);
			else
				cmd+=(bash -c);
			fi;
		elif ((is_scope_command)); then
			cmd+=(bash -c);
		fi;

		"${cmd[@]}" "bash -c $(printf %q "$(print_landing_script --mode run)")";
		fork_command_rc=$?;

		echo @@fork_command_rc;
		dump_bin <<<"$fork_command_rc";

	) | (

		# we handle file/folder transfers and other things here so
		# that it happens simultaneously accross all hosts, and thus
		# faster than one host at a time.  however we are in a
		# subshell.  temp_com_file is for information that must be
		# kept outside the subshell.

		handle_incoming_files_and_dirs_in_stream;

	) | (

		generic_message_handler;
		exit $?;

		while false IFS="" read -r line || [ -n "$line" ]; do
			case "$line" in
				(@panic)
					echo @panic;
					;;
				(@bliss)
					echo @bliss;
					;;
				(@@*)
					echo "$line";
					read_bin | dump_bin;
					;;
				(@*)
					echo "$line";
					;;
				(*)
					error "Unknown message received from sub kernel: '$line'. PANIC";
					echo @panic;
					break;
					;;
			esac;
		done;

	) > "$temp_com_file";

	# the landing process has its own "stream" of error messages other
	# than "stdout" "stderr" so that we catch and print these messages
	# only if rrssh was not provided the option to not panic on failed
	# ssh/su.
	local landing_msgs=(); # all errors.  the landing does not print any happy messages.
	local landing_failed=0;

	local bliss_received=0;
	local ignore_missing_bliss=0;
	local must_panic=0;
	local execution_total_args_shift=0;
	local scope_exitcode_received=0;
	local scope_exitcode=0;
	local fork_command_rc_received=0;
	local fork_command_rc=0;
	local landing_start_received=0;
	local kernel_start_received=0;
	while IFS="" read -r line || [ -n "$line" ]; do
		case "$line" in
			(@panic)
				must_panic=1;
				break;
				;;
			(@bliss)
				bliss_received=1;
				;;
			(@@total_toplevel_shift)
				execution_total_args_shift=$(read_bin);
				;;
			(@@scope_exitcode)
				scope_exitcode_received=1;
				scope_exitcode=$(read_bin);
				;;
			(@@fork_command_rc)
				fork_command_rc_received=1;
				fork_command_rc=$(read_bin);
				;;
			(@landing_start)
				landing_start_received=1;
				;;
			(@kernel_start)
				kernel_start_received=1;
				;;
			(@@print_landing_err)
				landing_msgs+=("$(read_bin)");
				;;
			(*)
				error "Unknown message received from sub kernel result parsing code: '$line'.";
				must_panic=1;
				break;
				;;
		esac;
	done < "$temp_com_file";
	rm -f "$temp_com_file";

	if ((must_panic)); then
		panic "Triggering a panic.";
	fi;

	if ((fork_command_rc_received)) && ! ((fork_command_rc == 0)); then

		# whether we received @landing_start is the difference between
		# a failing ssh/su VS the landing script that exited non-0
		# voluntarily.

		landing_failed=1;

		if ((landing_start_received)); then
			if ((kernel_start_received)); then
				landing_msgs+=(
					"The ssh or su command succeeded and the sub-kernel started, but something happened."
				);
			else
				landing_msgs+=(
					"The ssh or su command succeeded, but the sub-kernel could not be started during duplication."
				);
			fi;
		else
			landing_msgs+=(
				"The ssh or su command seems to fail."
				"Is an ssh key missing?"
				"Is ssh, su, or sudo prompting for a password?"
				"Is the destination resolving and reachable?"
				"Is there any spelling misatke?"
			);
		fi;
	elif ! ((landing_start_received)); then
		landing_failed=1;
		landing_msgs+=(
			"The ssh or su command seems to fail."
			"Is an ssh key missing?"
			"Is ssh, su, or sudo prompting for a password?"
			"Is the destination resolving and reachable?"
			"Is there any spelling misatke?"
		);
	elif ! ((kernel_start_received)); then
		landing_failed=1;
		landing_msgs+=(
			"The ssh or su command succeeded, but the kernel failed to start."
		);
	fi;

	if ((landing_failed)); then
		if ! ((opt_i)); then
			panic "${landing_msgs[@]}";
		else

			# MAYBE TODO: maybe we should still panic if we are a
			# simple scope and not a host or su command.

			ignore_missing_bliss=1;
			# instead of panicking, we behave like a scope that exited non-0.
			scope_exitcode_received=1;
			scope_exitcode=1;
		fi;
	fi;

	[ "$execution_total_args_shift" == "$total_scope_args_shift" ] || {

		# if the sub scope did not end because of a non-0 command, it
		# is normal that execution did not consume as many arguments
		# as pre-execution analysis.

		if ((scope_exitcode == 0)); then
			panic "The amount of token consumed during scope analysis is not equal as when executed.  scan: $total_scope_args_shift. execution: $execution_total_args_shift. bliss: $bliss_received. ";
		fi;
	};
	shift_toplevel_args "$total_scope_args_shift";

	if ! ((bliss_received)) && ! ((ignore_missing_bliss)); then
		panic "Sub kernel at remote host did not end blissfully.";
	fi;

	if ((scope_exitcode_received)); then
		return "$scope_exitcode";
	fi;

}

command_make_command_fail() {
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command 'make-command-fail' needs 1 argument.";
	};

	local id=$(peek_toplevel_args);
	shift_toplevel_args;

	current_command_must_run_p || return 0;

	make_command_fail_ids+=("$id");
}


command_cd() {
	local arg0=$(peek_toplevel_args);
	shift_toplevel_args;

	local path;
	case "$arg0" in
		(cd|pushd)
			any_toplevel_args_remaining || {
				panic "The command '$arg0' needs 1 argument.";
			};
			path=$(peek_toplevel_args);
			shift_toplevel_args;
			;;
	esac;

	current_command_must_run_p || return 0;

	case "$arg0" in
		(cd)
			cd -- "$path" || {
				error "Could not cd to '$path'.";
				return 1;
			};
			return 0;
			;;
		(home)
			cd || {
				error "Could not cd to home directory.";
				return 1;
			};
			return 0;
			;;
		(pushd)
			pushd -- "$path" || {
				error "Could not pushd to '$path'.";
				return 1;
			};
			return 0;
			;;
		(popd)
			popd || {
				error "Could not popd.";
				return 1;
			};
			return 0;
			;;
	esac;

}



command_drop_dir() {
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command 'drop-dir' needs 2 arguments.";
	};
	local drop_dir_name=$(peek_toplevel_args);
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command 'drop-dir' needs 2 arguments.";
	};
	local drop_dir_path=$(peek_toplevel_args);
	shift_toplevel_args;

	current_command_must_run_p || return 0;


}




command_take__file() {
	local source_path=$1;
	local dest_path=$2;
	local dest_drop_dir=$3;

	current_command_must_run_p || return 0;

	# TODO: read the output of generic_message_handler and
	# handle, in our current shell, @panic or other important
	# messages.

	(
		handle_incoming_files_and_dirs @@@@file 1 "$dest_drop_dir" "$dest_path" "$source_path";
	) | generic_message_handler;

}

command_take() {
	local arg0=$(peek_toplevel_args);
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command take needs 3 arguments.";
	};
	local obj_path=$(peek_toplevel_args);
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command take needs 3 arguments.";
	};
	local dest_path=$(peek_toplevel_args);
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command take needs 3 arguments.";
	};
	local dest_drop_dir=$(peek_toplevel_args);
	shift_toplevel_args;



    case "$arg0" in
		(take-file)
			command_take__file "$obj_path" "$dest_path" "$dest_drop_dir";
			;;
		(take-dir)
			true;
			;;
	esac;
}


main_execution_loop() {

	local current_toplevel_command;
	local current_command_rc=0;
	local current_command_reverse_rc=0;
	local current_chain_rc=0;
	local is_first_command_of_chain=1;
	local current_chain_has_try_prefix=0;
	local scope_closing_token_reached=0;
	local operator_used=0;

	skip_current_command_execution_flag=0;
	while any_toplevel_args_remaining; do
		current_command_rc=0;
		current_command_reverse_rc=0;
		operator_used=0;

		if ((is_first_command_of_chain)); then
			# TODO: consume scope closing token only if parent indicated to do so.
			if [ "$(peek_toplevel_args)" == "$toplevel_scope_closing_token" ]; then
				scope_closing_token_reached=1;
				shift_toplevel_args;
				break;
			fi;
		fi;

		if ((is_first_command_of_chain)); then
			if [ "$(peek_toplevel_args)" == try ]; then
				current_chain_has_try_prefix=1;
				shift_toplevel_args;
			fi;
		fi;

		if any_toplevel_args_remaining && [ "$(peek_toplevel_args)" == not ]; then
			current_command_reverse_rc=1;
			shift_toplevel_args;
		fi;

		if ! any_toplevel_args_remaining; then
			panic "An rrssh command must be provided after a prefix operator.";
		fi;
		current_toplevel_command=$(peek_toplevel_args);

		case "$current_toplevel_command" in
			(command|---)
				command_command;
				current_command_rc=$?;
				;;
			(host|sudo-host|su|sudo-su|"[")
				command_fork;
				current_command_rc=$?;
				;;
			(make-command-fail)
				command_make_command_fail;
				current_command_rc=$?;
				;;
			(true)
				shift_toplevel_args;
				current_command_rc=0;
				;;
			(false)
				shift_toplevel_args;
				current_command_rc=1;
				;;
			(cd|home|pushd|popd)
				command_cd;
				current_command_rc=$?;
				;;
			(take-file|take-dir)
				command_take;
				current_command_rc=$?;
				;;
			(debug)
				shift_toplevel_args;
				if current_command_must_run_p; then
					echoout "ASDF";
				fi;
				;;
			(delim)
				shift_toplevel_args;
				if current_command_must_run_p; then
					echoout "====";
				fi;
				;;
			(pwd)
				shift_toplevel_args;
				if current_command_must_run_p; then
					pwd | send_to_stdout;
				fi;
				;;
			(*)
				echocom @@exitcode;
				dump_bin <<<"1" 1>&3;
				panic "Invalid rrssh command: '$current_toplevel_command'.";
				;;
		esac;
		is_first_command_of_chain=0;
		if ((current_command_reverse_rc)); then
			current_command_rc=$((! current_command_rc));
		fi;

		# if the command had to run, its return code is now the
		# current return code of the command chain.
		if current_command_must_run_p; then
			current_chain_rc=$current_command_rc;
		fi;

		if any_toplevel_args_remaining; then
			case "$(peek_toplevel_args)" in
				(and)
					operator_used=1;
					skip_current_command_execution_flag=$current_chain_rc;
					;;
				(or)
					operator_used=1;
					skip_current_command_execution_flag=$((! current_chain_rc));
					;;
			esac;
			if ((operator_used)); then
				shift_toplevel_args;
				if ! any_toplevel_args_remaining; then
					panic "An rrssh command must be provided after an infix operator.";
				fi;
				continue;
			fi;
		fi;

		# when execution reaches here, we have completed a complete "command chain"
		if ! ((current_chain_has_try_prefix)) && ! ((current_chain_rc == 0)); then
			if ((opt_p)) || ((is_root_kernel)); then
				echocom @@exitcode;
				dump_bin <<<"$current_chain_rc" 1>&3;
				# TODO: add command chain and line number to error message
				panic "The command chain exited non-0.";
			else
				echocom @@scope_exitcode;
				dump_bin <<<"$current_chain_rc" 1>&3;

				# we need to stop execution early and return to the
				# body of main() so that we echocom @bliss to indicate
				# we terminated properly, however we have to skip the
				# code that ensures that the while loop terminated
				# before we reached an ending token.

				# break;
				return 1;

			fi;
		fi;

		# now we reset flags for the next "command chain".
		is_first_command_of_chain=1;
		skip_current_command_execution_flag=0;
		current_chain_has_try_prefix=0;
		current_chain_rc=0;

	done;

	if ! ((is_root_kernel)); then
		if ! ((scope_closing_token_reached)); then
			panic "The scope must end with a closing token $toplevel_scope_closing_token";
		fi;
	fi;

}


main() {
	load_eof_values;

	main_execution_loop;

	if ! ((is_root_kernel)); then
		echocom @@total_toplevel_shift;
		dump_bin <<<"$total_toplevel_args_shift_count" 1>&3;
	fi;
	echocom @bliss;
}

main;
exit "$?";

KERNEL
	
}




# THE script to be executed.
toplevel_commands=();
toplevel_commands_provided=0;

read_toplevel_commands_from_file() {
	local filepath=$1;
	local current_line_number=1;
	local output_file=$(mktemp);
	local temp_script_path;
	local line;
	local word;
	local parsed_word;
	while IFS="" read -r line || [ -n "$line" ]; do
		temp_script_path=$(mktemp);
		{
			# printf %q ensure that all arguments are only one line
			# when printed.
			cat <<"SCRIPT";
				print_args() {
					(($# > 0)) && printf %q\\n "$@";
					exit 0;
				}
SCRIPT
			printf %s\\n "print_args $line";
		} > "$temp_script_path";

		bash -s -n < "$temp_script_path" &> /dev/null || {
			rm -f "$temp_script_path";
			1>&2 echo "Error in file '$filepath' on line $current_line_number.";
			exit 1;
		};
		bash -s < "$temp_script_path" > "$output_file";
		rm -f "$temp_script_path";

		while IFS="" read -r word || [ -n "$word" ]; do
			parsed_word="$(
				# subshell for safety.
				eval "output=$word";
				printf %s "$output";
			)";
			toplevel_commands+=("$parsed_word");
		done < "$output_file";

		((current_line_number++));
	done < "$filepath";
	rm -f "$output_file";
	
	toplevel_commands_provided=1;
}
read_toplevel_commands_from_arguments() {
	toplevel_commands=("${arg_script[@]}");
	toplevel_commands_provided=1;
}



begin_root_kernel() {
	print_kernel;
	echo;
	echo "###;;;";
	
	for toplevel_arg in "${toplevel_commands[@]}"; do
		echo @@toplevel_arg;
		dump_bin <<<"$toplevel_arg";
	done;

	for id in "${make_command_fail_ids[@]}"; do
		echo @@make_command_fail_id;
		dump_bin <<<"$id";
	done;

	((opt_p)) && echo @opt_p;
	((opt_i)) && echo @opt_i;
	((opt_fake_su)) && echo @fake_su;

	echo @@rrssh_id;
	tr -dc 0123456789abcdefghijklmnopqrstuvwxyz < /dev/urandom | head -c 10 | dump_bin;
	echo @@rrssh_fork_depth;
	dump_bin <<<"0";
	echo @@rrssh_host_depth;
	dump_bin <<<"0";
	
	echo @end_of_header;
}

run_root_kernel_mode() {
	local mode=$1;

	local temp_kernel_path=$(mktemp);
	(

		begin_root_kernel;

	) > "$temp_kernel_path";
	local temp_com_file=$(mktemp);
	bash "$temp_kernel_path" -- --mode "$mode" --root 2> /dev/null | (
		while IFS="" read -r line || [ -n "$line" ]; do
			case "$line" in
				(@@print_stdout)
					read_bin;
					;;
				(@@print_stderr)
					read_bin 1>&2;
					;;
				(@bliss)
					echo @bliss >> "$temp_com_file";
					;;
				(@@exitcode)
					echo @@exitcode >> "$temp_com_file";
					read_bin | dump_bin >> "$temp_com_file";
					;;
				(@panic)
					echo @panic >> "$temp_com_file";
					;;
				(@kernel_start)
					true; # we do nothing
					;;
				(*)
					1>&2 echo "Unknown object in kernel output: $line";
					# MAYBE TODO: throw a real error?
					;;
			esac;
		done;
	);
	rm -f "$temp_kernel_path";

	local exitcode_received=0;
	local exitcode=0;
	local panic_received=0;
	local bliss_received=0;
	while IFS="" read -r line || [ -n "$line" ]; do
		case "$line" in
			(@@exitcode)
				exitcode_received=1;
				exitcode=$(read_bin);
				# read_line;
				;;
			(@bliss)
				bliss_received=1;
				;;
			(@panic)
				panic_received=1;
				;;
		esac;
	done < "$temp_com_file";
	rm -f "$temp_com_file";

	if ((panic_received)); then
		if ((exitcode_received)); then
			return "$exitcode";
		else
			return 1;
		fi;
	fi;

	if ! ((bliss_received)); then
		1>&2 echo "PROBLEM: The root subkernel did not end blissfully";
		return 1;
	fi;
}

command_check() {
	((toplevel_commands_provided)) || {
		1>&2 echo "You must provide a rrssh script.";
		return 1;
	};

	run_root_kernel_mode scan;
}

command_run() {
	command_check || return 1;

	run_root_kernel_mode run;
}

main() {
	if (($# == 0)); then
		echo "You must provide a command.";
		return 1;
	fi;
	local cmd=$1;

	if ((opt_file)); then
		local temp_script_file_path=$(mktemp);
		if [ "$arg_file" == "-" ]; then
		    cat > "$temp_script_file_path";
		else
			cat -- "$arg_file" > "$temp_script_file_path";
		fi;
		read_toplevel_commands_from_file "$temp_script_file_path";
		rm -f "$temp_script_file_path";
	elif ((opt_script_provided)); then
		read_toplevel_commands_from_arguments;
	fi

	shift;
	case "$cmd" in
		(print-kernel)
			print_kernel;
			;;
		(run)
			command_run;
			;;
		(check)
			command_check;
			;;
		(print)
			((toplevel_commands_provided)) || {
				1>&2 echo "You need to provide a script";
				return 1;
			};
			if ((opt_t)); then
				echo "${#toplevel_commands[@]}";
			else
				local printf_arg=$(((opt_l)) && echo '%s\n' || echo '%q\n');
				if ((opt_n)); then
					((arg_n < ${#toplevel_commands[@]})) || {
						1>&2 echo "The value provided to -n is larger than the number of tokens.";
						return 1;
					};
					printf "$printf_arg" "${toplevel_commands[$arg_n]}";
				else
					printf "$printf_arg" "${toplevel_commands[@]}";
				fi;
			fi;
			;;
		(*)
			1>&2 echo "Unknown command '$cmd'.";
			return 1;
			;;
	esac;
}


main "$@";
exit "$?";

