#!/usr/bin/env bash

# MUST: Process substitution are not allowed.  Older container
# technologies prior to docker breaks process substitutions inside
# them.

# MUST: Support older bash versions.  No fancy features other than
# basic list manipulations.

# TODO: un pretty printer

# TODO: améliorer l'anglais dans le message d'aide.

# TODO: différentes versions de bash

# TODO: set-env unset-env


help() {
	cat <<"HELP";
NAME

	rrssh - remote recursive ssh

SYNOPSIS

	rrssh [<options>...] <main-command> [--- <rrssh commands>...]

DESCRIPTION

	An automation tool that uses SSH to jump through any number of
	hosts to run commands and transfer files and directories along the
	way.  Its commands are a basic shell-like scripting language
	provided via arguments or a file.  The panic mechanism will stop
	its execution on any unhandled failure in the script, or an
	internal rrssh failure.

	The only requirements for the target hosts are an old bash version
	and basic utilities.

SAFETY CONSIDERATIONS

	rrssh is a bash script that duplicates itself via ssh.  To
	guarentee the termination of all rrssh scripts, its language is
	not Turing-complete and does not allow infinite loops.  The whole
	syntax of the script is validated before execution starts, and the
	syntax is validated by the same code that executes the script to
	ensure identical interpretation of the code.

	In some occasions, such as before and after each rrssh command, a
	message is sent from its current location up to the "root"
	command, which replies with a message to either continue or panic.
	This mechanism (internally called epoll_panic) allows Ctrl-C on
	the "root" command to recursively kill its execution (though not
	before any external command is completed and a new message is
	sent).  This mecanism also forces rrssh to crash if any host in
	the "chain" becomes unreachable for any reason.  Worst case
	scenario would be that rrssh will hang idle infinitely instead of
	dying.  An additionnal crashing mechanism is that stderr is keept
	connected at all times up to the "root" command, and rrssh will
	attempt to write trash data during long operations in case a
	network failure with a parent host eventually leads to receiving a
	SIGPIPE, thus crashing faster.

	TODO: make sure que j'ai bien implémenté les écritures dans fd 2.

	From the beginning, rrssh has a first-class panic system that
	immediately stops its execution when triggered.  The panic system
	was not an afterthought.  rrssh is also built to be highly
	testable, and its test suite is extensive.  For example, the test
	suite performs fault injection to verify that all important error
	paths successfuly trigger the panic mechanism and that no further
	commands are executed.  rrssh includes a missing code coverage
	detection capability to verify that there is a least one test for
	all important error paths.

	To ensure quality, no AI is used to develop rrssh.  It may be used
	only to scan for bugs.

MAIN COMMANDS

	For the main commands that need a script, the script must be
	provided either with the option --- or -f.

	run

		Run the script.

	check

		Examine the script for syntax errors and other problems
		without running it.

	print [-n <index>] [-lt]

		Prints the script, one token per line.  With -n, only print
		that token.  Tokens are indexed at 0.  With -t, only print the
		amount of tokens.  With -l, do not quote the tokens using
		printf %q.

	print-kernel

		Duplicates the kernel to stdout.  Send it to shellcheck for
		analysis.

OPTIONS

	-h, --help

		Show this help message.

	--- <commands>...

		Stop reading options and arguments.  The remaining arguments
		will be interpreted as a script.  --- is necessary if the
		script is provided by arguments.

	-f, --file <filepath>

		Provide a file of commands to execute instead of reading from
		the arguments.  If file is "-", then read from stdin.

		When writing a script file, type words and tokens like you
		would in a shell script.  rrssh parses the file line by line
		with eval so that bash handles all forms of expansions like
		brace expansion, tilde expansion, and command substitution,
		for example.  This way, rrssh can read ANSI-C single quoted
		sequences. If you include a rrssh script in an unquoted here
		document in a standard shell script, use printf %q to properly
		escape all variables inside the here document.  See the
		examples below.

	-p

		Make any command chain that does not exit with 0 trigger a
		rrssh panic.  Default behavior is to only make the parent
		scope exit non-0.

	-i

		Any command host or su that fails will be handled as if their
		internal scope had exited non-0 instead of triggering a panic.

	-n <index>

		Read the description of the command "print".

	-l, -t

		Read the description of the command "print".

EXECUTION

	A rrssh script is usually made of scopes [ ].  Unlike normal
	shells, by default, any command "chain" that exits non-0 will stop
	further execution of the scope and the scope will exit with non-0.
	The -p option will make rrssh panic instead.  By default, any host
	or su command that fails will trigger a panic unless the option -i
	is used.  With -i, a failing host or su command will behave as if
	its inner scope exited non-0.

COMMANDS

	host <destination> [-o <option=value>]... [ <commands>... ]
	host <destination> [-o <option=value>]... : <commands>...
	sudo-host <destination> [-o <option=value>]... [ <commands>... ]
	sudo-host <destination> [-o <option=value>]... : <commands>...

		These commands are the main purpose of using rrssh.
		Duplicates the rrssh kernel through a single ssh connection
		and execute the sub commands on the remote host.  This command
		can include itself arbitrarily many times to reach any depth
		in a network.  The [ ] variants are scoped.  The : variants
		take all the commands until the end of the current scope.  The
		sudo variants will run the actual ssh command through sudo.

	    Options provided using -o will be forwarded to the ssh
	    command.  The following options will always be provided to
	    ssh: ConnectTimeout=10 ServerAliveInterval=15.

		Ex: host appserver1 -o Port=10022 [ --- ls --- ]

	su <user> [ <commands>... ]
	su <user> : <commands>...
	sudo-su <user> [ <commands>... ]
	sudo-su <user> : <commands>...

		Same as the host command, but switches user on the same
		host instead.

	[ <commands>... ]

		Create a subscope and run commands inside.  This is the
		equivalent of a subshell in shell scripting.

	command <system-command>
	command [ <argv>... ]
	--- <argv>... ---

		Call an external command.  Stdout and stderr are currently
		mixed together into rrssh's stdout.  /dev/null will be the
		command's stdin.

	true
	false

		Do nothing, with success or failure.

	print <text>

		Print a line of text to stdout.

	panic <text>

		Trigger rrssh's panic mechanism with the given message.  This
		command makes the execution stop.

	cd <path>
	home
	pushd <path>
	popd

		Change your current directory.

	pwd

		Print the current working directory.

	take-file <path> <new-name> <dropdir>
	take-dir <path> <new-name> <dropdir>

		Bring a file or directory to a drop directory on the current
		host, a parent host, or a future child host.  You can provide
		a new name for the file or directory.  You can preserve the
		current name by providing an empty argument as the name ("").

	drop-dir <name> <path>

		Indicate a drop directory (and its name) to receive files and
		directories taken with take-file or take-dir.  The parent
		directory must already exist.

OPERATORS

	The general syntax of a "command chain" is as follows:

		[try] [not] <command> [(and|or) [not] <command>]...

infix operators

	and
	or

		Run the next command of the chain only if the current exit
		code of the chain is a success or failure.  Behaves exactly
		like && and || in shell scripting.

prefix operators

	not <command>

		Inverses the exit code of the following command.  Behaves like
		preceeding a command with a ! in a shell script.

	try

		Ignore the exit code of the following command chain.  Default
		behavior is when a command chain exits non-0.

OPTIONS USED BY RRSSH'S TEST SUITE

	--make-command-fail <id>

		Do not use this.  This is intended for the test suite.  Makes
		a command fail to validate the behavior of the error paths.

	--fake-su

		Do not use this.  This is intended for the test suite.  Make
		the su commands not really attempt to switch user to prevent
		passwords from breaking the test suite.

COMMANDS USED BY RRSSH'S TEST SUITE

	make-command-fail <id>

		Do not use this.  This is intended for the test suite.  Makes
		a command fail to validate the behavior of the error paths.
		This will be in effect only for the current scope and all
		child scopes.

	kernel-inner-function [--] [<arguments>]...

		Do not use this.  This is intended for the test suite.
		Instead of running the main loop, call an internal kernel
		function, print its output and return its exit code.  This is
		used for helper functions that don't have side effects.

ENVIRONMENT VARIABLES USED FOR DEVELOPMENT

	RRSSH_COVERAGE_FILE

		If defined, file path to append code coverage ids encountered.

EXAMPLES

	TODO

PROBLEMS

	TODO

HELP
}

unimplemented_wishlist() {
	# shellcheck disable=SC2317
	cat <<"HELP";


	pretty-print

		Pretty prints the script for an easier visual analysis.

	walk

		Try going through all the hosts and all the user switchings,
		without running any commands.




	for <variable> in <values>... [ <commands>... ]
	for <variable> <delim> <values>... <delim> <command>
	for <variable> <delim> <values>... <delim> [ <commands>... ]
	for <variable> --- <values>... --- <command>
	for <variable> --- <values>... --- [ <commands>... ]

		Loop a block of code over some values.  Each time, all
		instances of <variable> in the commands will be substituted.
		Use special symbols to avoid replacing unwanted parts of the
		commands.  You cannot replace syntax elements of the language
		with variables.

	var <variable> <value>

		Create a variable.  The variable is available and affectable
		in the current scope and all child scopes.  You cannot create
		a variable if its name already exists in the current scope.
		Use the hosts' "test" command with rrssh's "command" command
		to compare its value.

	set-var <variable> <value>

		Change the value of a variable.  The variable must have
		previously been created with the var command in the current
		scope or a parent scope.

	if <command> then <command>
			[ elif <command> then <command> ]...
			[ else <command> then <command> ]
			fi

		TODO



pour implémenter les if et les scopes, il faut donner au nouveau
kernel le token qui met fin à son scope (pour les scope) et une option
qui indique qu'il doit rouler une seule commande (pour les if).


HELP
}


opt_file=0;
arg_file="";

opt_n=0;
arg_n="";

opt_l=0;
opt_t=0;
opt_p=0;
opt_i=0;
opt_fake_su=0;

opt_script_provided=0;
arg_script=();

make_command_fail_ids=();

trailing_args=();
while (($#)); do
	arg=$1;
	shift;
	case "$arg" in
		(-h|--help)
			help;
			exit 0;
			;;
		(---)
			opt_script_provided=1;
			arg_script=("$@");
			set --;
			break;
			;;
		(--)
			break;
			;;
		(-f|--file)
			opt_file=1;
			arg_file=$1;
			shift;
			;;
		(-n)
			opt_n=1;
			arg_n=$1;
			[[ "$arg_n" =~ ^[0-9]+$ ]] || {
				1>&2 echo "The value provided to -n must be numeric and positive.";
				exit 1;
			};
			shift;
		    ;;
		(-l)
			opt_l=1;
			;;
		(-t)
			opt_t=1;
			;;
		(-p)
			opt_p=1;
			;;
		(-i)
			opt_i=1;
			;;
		(--fake-su)
			opt_fake_su=1;
			;;
		(--make-command-fail)
			make_command_fail_ids+=("$1");
			shift;
			;;
		(*)
			trailing_args+=("$arg");
			;;
	esac
done;
set -- "${trailing_args[@]}" "$@";
unset trailing_args;
unset arg;


testable() {
	local command_id=$1;
	shift;
    local id;
	for id in "${make_command_fail_ids[@]}"; do
		if [ "$id" == "$command_id" ]; then
			return 1;
		fi;
	done;
	"$@";
}
testable id_asdgierguirh true;


dump_bin() {
	echo %binary_object;
	# MAYBE TODO: i probably have to send useless chars and read them
	# back because base64 doesn't seem to handle an actual empty
	# stream.
	base64 -w 10000;
	echo %end;
}
read_line() {
	local IFS="";
	local line;
	read -r line;
	printf %s "$line";
}
# read_line_ln() {
# 	printf '%s\n' "$(read_line)";
# }
read_bin() {
	local first_line;
	first_line=$(read_line);
	[ "$first_line" == %binary_object ] || return 1;
	{
		while IFS="" read -r line || [ -n "$line" ]; do
			[ "$line" == %end ] && break;
			printf %s "$line";
		done;
	} | base64 --decode;
}

read_bin_pipe_dump_bin() {
	local first_line;
	first_line=$(read_line);
	[ "$first_line" == %binary_object ] || return 1;
	echo "$first_line";
	local line;
	while IFS="" read -r line || [ -n "$line" ]; do
		echo . 1>&2;
		[ "$line" == %end ] && {
			echo %end;
			break;
		};
		printf %s\\n "$line";
	done;
}


mktemp_fifo() {
	local temp_file;
	temp_file=$(mktemp) || {
		return 1;
	};
	rm -f -- "$temp_file" || {
		return 1;
	};
	mkfifo -- "$temp_file" || {
		return 1;
	};
	printf '%s\n' "$temp_file";
}

print_kernel() {
	cat <<"KERNEL";
#!/bin/bash

# The shebang line is for shellcheck

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd);
KERNEL_PATH=$SCRIPT_DIR/${0##*/};

# for optimization purposes, files and directories may not be
# duplicated to us to avoid wasting space.  we may be instructed to
# take our objects from a different kernel on the same host.

HEAVY_OBJECTS_KERNEL_PATH=$KERNEL_PATH;

# stdout for communication.  stderr for accidental garbage and trying
# to raise a sigpipe.  stdout is moved to 3 to avoid accidental
# garbage from breaking the protocol.
exec 3>&1 1>&2 5>&0 0< /dev/null;

# 0 = /dev/null
# 1 = garbage
# 2 = garbage
# 3 = protocol out (our initial stdout)
# 4 = reserved for possible futur use
# 5 = our stdin, from the parent kernel

# 6 = subkernel's stdin
# 7 = subkernel's protocol output (stdout)

# IIRC, the bash manual says to not use numbers above 9.



KERNEL

	declare -f dump_bin;
	declare -f read_line;
	# declare -f read_line_ln;
	declare -f read_bin;
	declare -f read_bin_pipe_dump_bin;
	declare -f print_kernel;
	declare -f testable;
	declare -f mktemp_fifo;

	cat <<"KERNEL";


echocom() {
	echo "$@" 1>&3;
}
pipeline_echocom() {
	echo "$@";
}

echocom @kernel_start;

send_to_stdout() {
	echocom @@print_stdout;
	dump_bin 1>&3;
}
send_to_stderr() {
	echocom @@print_stderr;
	dump_bin 1>&3;
}

pipeline_send_to_stdout() {
	# shellcheck disable=SC2317
	echo @@print_stdout;
	# shellcheck disable=SC2317
	dump_bin;
}
pipeline_send_to_stderr() {
	echo @@print_stderr;
	dump_bin;
}

echoout() {
	# shellcheck disable=SC2059,SC2317
	echo "$@" | send_to_stdout;
}
printfout() {
	# shellcheck disable=SC2059,SC2317
	printf "$@" | send_to_stdout;
}

pipeline_echoout() {
	# shellcheck disable=SC2059,SC2317
	echo "$@" | pipeline_send_to_stdout;
}
pipeline_printfout() {
	# shellcheck disable=SC2059,SC2317
	printf "$@" | pipeline_send_to_stdout;
}

echoerr() {
	# shellcheck disable=SC2059,SC2317
	echo "$@" | send_to_stderr;
}
printferr() {
	# shellcheck disable=SC2059 # i actually want a printf to stderr without doing 1>&2
	printf "$@" | send_to_stderr;
}

pipeline_echoerr() {
	# shellcheck disable=SC2059,SC2317
	echo "$@" | pipeline_send_to_stderr;
}
pipeline_printferr() {
	# shellcheck disable=SC2059
	printf "$@" | pipeline_send_to_stderr;
}


# calling panic from inside a subshell will not cause rrssh to stop automatically!
panic() {
	printferr 'PANIC: %s PANIC\n' "$@";
	echocom @panic;
	exit 1;
}
error() {
	printferr 'ERROR: %s ERROR\n' "$@";
}
debug() {
	# shellcheck disable=SC2317
	true || return 0;
	# shellcheck disable=SC2317
	printferr 'DEBUG: %s DEBUG\n' "$@";
}

pipeline_panic() {
	pipeline_printferr 'PANIC: %s PANIC\n' "$@";
	pipeline_echocom @panic;
	exit 1;
}
pipeline_error() {
	# shellcheck disable=SC2317
	pipeline_printferr 'ERROR: %s ERROR\n' "$@";
}
pipeline_debug() {
	# shellcheck disable=SC2317
	pipeline_printferr 'DEBUG: %s DEBUG\n' "$@";
}


pipeline_coverage() {
	local coverage_id=$1;
	# enforce that ids begin with "id_" so that they are detectable
	# with grep.
	[[ "$coverage_id" == id_* ]] || exit 1;
	echo @@coverage;
	dump_bin <<<"$coverage_id";
}
coverage() {
	pipeline_coverage "$@" 1>&3;
}



# the multiple "operation modes" of the kernel are for scanning or
# other details without having to duplicate code.

# The calling protocol of the kernel never requires the whole user
# script to be provided by arguments because it may be
# "dangerously" long (i dont know whether there is a platform with an
# argument limit) or it may contain credentials (must not show up in
# ps aux).

# The user script, files and directories to transmit, most information
# and other "object" types must be provided at the end of the kernel
# script.  Some basic information like the "operation mode" is
# provided via arguments, though.  The line "###;;;" indicates the end
# of the kernel and the beginning of the objects.  First we put all
# small-ish object, which is anything other than files and folders,
# then a separator, then we dump files and folders.  This is to avoid
# the need to skip large files/folders and thus speed up a little bit.



rrssh_id=""; # unique id for the whole runtime
rrssh_fork_depth=0;
rrssh_host_depth=0;


# to be used by code that really needs to check a pipe for errors.
PIPESTATUS_BACKUP=();
pipestatus_save() {
	PIPESTATUS_BACKUP=("${PIPESTATUS[@]}");
}
pipestatus_debug() {
	# shellcheck disable=SC2317
	debug "PIPESTATUS_BACKUP: ${PIPESTATUS_BACKUP[*]}";
}
# prints the index of the first non-0 exit code, and return with that
# code.  if given an index, instead print the exitcode.
pipestatus_check() {
	local index=$1;
	if [ -n "$index" ]; then
		if ((index <= ${#PIPESTATUS_BACKUP[@]})); then
			echo "${PIPESTATUS_BACKUP[index]}";
			return "${PIPESTATUS_BACKUP[index]}";
		else
			error "PROBLEM WITH INDEX GIVEN TO pipestatus_check";
			exit 1;
		fi;
	fi;
	local i;
	for ((i = 0; i < ${#PIPESTATUS_BACKUP[@]}; i++)); do
		if ((PIPESTATUS_BACKUP[i] > 0)); then
			echo "$i";
			return "${PIPESTATUS_BACKUP[i]}";
		fi;
	done;
	return 0;
}
pipestatus_test() {
	pipestatus_check "$@" &> /dev/null;
}


# operation mode
op_mode=""; # enum of: run scan kernel-inner-function

# kernel-inner-function mode allows the test suite to call an internal
# function directly and get its output and its exit code.

# are we the first kernel?  therefore we dont have a parent scope.
is_root_kernel=0;

# are we suposed to run only one command chain?
# is_one_command_chain_limit=0;

# if we have stdin, then we have 2 way communication.
opt_stdin=0;


# the rrssh kernel supports being recycled.  this allows for a much
# faster scan mode.  if we are a recycled kernel, we must ignore some
# @ messages given that parent, and we receive these equivalent
# through arguments.

opt_recycled=0;
extra_messages=();
recycling_base_toplevel_skip=0;



kernel_inner_function_args=();


while (($#)); do
	arg=$1;
	shift;
	case "$arg" in
		(--mode)
			op_mode=$1;
			shift;
			;;
		(--root)
			is_root_kernel=1;
			;;
		(--one-command-chain-limit)
			# is_one_command_chain_limit=1;
			true;
			;;
		(--stdin)
			opt_stdin=1;
			;;
		(--recycled)
			opt_recycled=1;
			;;
		(-x|--extra-message)
			extra_messages+=("$1");
			shift;
			;;
		(--recycling_base_toplevel_skip)
			recycling_base_toplevel_skip=$1;
			shift;
			;;
	esac;
done;
unset arg;


# checks whether any parent kernels wants to trigger the panic
# mecanism.  do not call from inside a subshell, we don't have
# guarentee that we are the only one reading our kernel's stdin, and
# we use fd 3.

# returns true if we must panic
epoll_panic() {
	((opt_stdin)) || return 1;
	[ "$op_mode" == scan ] && return 1;
	[ "$op_mode" == walk ] && return 1;

	echocom @epoll_panic;
	local line;
	while IFS="" read -r line || [ -n "$line" ]; do
		case "$line" in
			(@continue)
				return 1;
				;;
			(*)
				return 0;
				;;
		esac;
		# break;
	done 0<&5;
}
epoll_panic && {
	panic "epoll indicated to panic.";
};


# hoenn

# if we are not the root kernel, then this is the token that's gonna
# close our scope.  if empty, then we dont have a closing token.
toplevel_scope_closing_token="";

consume_toplevel_scope_closing_token=0;


toplevel_args=();
total_toplevel_args_shift_count=0;



make_command_fail_ids=();

opt_p=0;
opt_i=0;
opt_fake_su=0;

shift_toplevel_args() {
	local shift_count=${1:-1};
	set -- "${toplevel_args[@]}";
	shift "$shift_count";
	toplevel_args=("$@");
	((total_toplevel_args_shift_count += shift_count));
}
peek_toplevel_args() {
	printf %s "${toplevel_args[0]}";
}
any_toplevel_args_remaining() {
	((${#toplevel_args[@]} > 0));
}

skip_kernel() {
	local line;
	while IFS="" read -r line || [ -n "$line" ]; do
		[ "$line" == "###;;;" ] && break;
	done;
}
skip_to_heavy_objects() {
	local line;
	while IFS="" read -r line || [ -n "$line" ]; do
		case "$line" in
			(@end_of_header)
				break;
				;;
			(@@*)
				read_bin_pipe_dump_bin > /dev/null;
				;;
			(@*)
				true;
				;;
		esac;
	done;
}
load_extra_messages() {
	set -- "${extra_messages[@]}";
	local arg;
	while (($#)); do
		arg=$1;
		shift;
		case "$arg" in 
			(@@toplevel_scope_closing_token)
				toplevel_scope_closing_token=$1;
				shift;
				;;
			(@consume_toplevel_scope_closing_token)
				consume_toplevel_scope_closing_token=1;
				;;
			(@@rrssh_fork_depth)
				rrssh_fork_depth=$1;
				shift;
				;;
			(@@rrssh_host_depth)
				rrssh_host_depth=$1;
				shift;
				;;
			(*)
				panic "Unknown message '$arg' in extra_messages.";
				;;
		esac;
	done;
}
load_eof_values() {
	local object_type;
	local eof_encountered=0;
	{
		skip_kernel;
		while IFS="" read -r object_type || [ -n "$object_type" ]; do
			case "$object_type" in
				(@end_of_header)
					break;
					;;
				(@panic)
					panic "Previous kernel wanted to panic during duplication.";
					;;
				(@@print_stdout)
					if ! ((opt_recycled)); then
						echocom @@print_stdout;
						read_bin_pipe_dump_bin 1>&3;
					else
						read_bin_pipe_dump_bin > /dev/null;
					fi;
					;;
				(@@print_stderr)
					if ! ((opt_recycled)); then
						echocom @@print_stderr;
						read_bin_pipe_dump_bin 1>&3;
					else
						read_bin_pipe_dump_bin > /dev/null;
					fi;
					;;
				(@@toplevel_arg)
					toplevel_args+=("$(read_bin)");
					;;
				(@@toplevel_scope_closing_token)
					toplevel_scope_closing_token=$(read_bin);
					;;
				(@@rrssh_id)
					rrssh_id=$(read_bin);
					;;
				(@@rrssh_fork_depth)
					rrssh_fork_depth=$(read_bin);
					;;
				(@@rrssh_host_depth)
					rrssh_host_depth=$(read_bin);
					;;
				(@opt_p)
					opt_p=1;
					;;
				(@opt_i)
					opt_i=1;
					;;
				(@fake_su)
					opt_fake_su=1;
					;;
				(@consume_toplevel_scope_closing_token)
					if ! ((opt_recycled)); then
						consume_toplevel_scope_closing_token=1;
					fi;
					;;
				(@@make_command_fail_id)
					make_command_fail_ids+=("$(read_bin)");
					;;
				(@@@@@take_obj)
					localhost_taken_dest_dropdirs+=("$(read_bin)");
					localhost_taken_types+=("$(read_bin)");
					localhost_taken_dest_names+=("$(read_bin)");
					localhost_taken_source_paths+=("$(read_bin)");
					;;
				(@@heavy_objects_kernel_path)
					HEAVY_OBJECTS_KERNEL_PATH=$(read_bin);
					;;
				(@@@add_dropdir)
					localhost_dropdirs_names+=("$(read_bin)");
					localhost_dropdirs_paths+=("$(read_bin)");
					;;
				(@@parent_dropdir)
					parents_dropdirs+=("$(read_bin)");
					;;
				(@@coverage)
					echocom @@coverage;
					read_bin_pipe_dump_bin 1>&3;
					;;
				(@@kernel_inner_function_arg)
					kernel_inner_function_args+=("$(read_bin)");
					;;
				(*)
					panic "Unknown object in kernel dump: '$object_type'.";
					;;
			esac;
		done;
		load_extra_messages;
		# if we are a recycled kernel, then the rest was already validated
		if ((opt_recycled)); then
			eof_encountered=1;
			return 0;
		fi;
		while IFS="" read -r object_type || [ -n "$object_type" ]; do
			case "$object_type" in
				(@panic)
					panic "The previous kernel wanted to panic during duplication.";
					;;
				(@@print_stdout)
					echocom @@print_stdout;
					read_bin_pipe_dump_bin 1>&3;
					;;
				(@@print_stderr)
					echocom @@print_stderr;
					read_bin_pipe_dump_bin 1>&3;
					;;
				(@eof)
					eof_encountered=1;
					break;
					;;
				(@@@@file|@@@@dir)
					read_bin_pipe_dump_bin > /dev/null;
					read_bin_pipe_dump_bin > /dev/null;
					read_bin_pipe_dump_bin > /dev/null;
					;;
				(@@coverage)
					echocom @@coverage;
					read_bin_pipe_dump_bin 1>&3;
					;;
				(*)
					panic "Unknown object in kernel dump: '$object_type'.";
					;;
			esac;
		done;
	} < "$KERNEL_PATH";

	# this ensures that we dont run if the connection was broken
	# during duplication.
	if ! ((eof_encountered)); then
		panic "The end of file token was not in the kernel dump.";
	fi;
}




# i dont trust bash hashes with user inputs.  therefore everything
# relating to files and dirs is stored is different lists of equal
# lengths at all times, where the same index in each list is a
# different property of the same object.

# we try to save everything as absolute paths, because we want to let
# the user change directories.

localhost_dropdirs_names=();
localhost_dropdirs_paths=();

localhost_taken_dest_dropdirs=();
localhost_taken_types=(); # either a string "f" or "d"
localhost_taken_dest_names=();
localhost_taken_source_paths=();





# drop directory names used by all our parents.  used to know whether
# we need to send files and dirs upward.  dupplicates in this list are
# not a concern.

parents_dropdirs=();


# indicates whether $1 is in the list, provided by all the trailing
# arguments.
is_item_in_list() {
	local item=$1;
	shift;
	local arg;
	for arg in "$@"; do
		[ "$arg" == "$item" ] && return 0;
	done;
	return 1;
}



begin_basic_fork() {
	print_kernel;
	echo;
	echo '###;;;';

	local token;
	for token in "${toplevel_args[@]}"; do
		echo @@toplevel_arg;
		dump_bin <<<"$token";
	done;

	local id;
	for id in "${make_command_fail_ids[@]}"; do
		echo @@make_command_fail_id;
		dump_bin <<<"$id";
	done;

	((opt_p)) && echo @opt_p;
	((opt_i)) && echo @opt_i;
	((opt_fake_su)) && echo @fake_su;

	echo @@rrssh_id;
	dump_bin <<<"$rrssh_id";
	echo @@rrssh_fork_depth;
	dump_bin <<<$((rrssh_fork_depth + 1));

}





identity_function() {
	local ret=$1;
	shift;
	printfout '%s\n' "$@";
	return "$ret";
}

sanitize_path() {
	local ret=$1;
	[ -z "$ret" ] && return 1;
	# MAYBE TODO: write this "correctly" with temp variables.
	local i;
	for ((i = 0; i < 20; i++)); do
		ret=${ret//"//"/"/"};
	done;
	ret=${ret%/};
	ret=${ret%/};
	ret=${ret%/};
	[ -z "$ret" ] && ret=/;
	printf %s\\n "$ret";
}

# the parent directory must exist because we just use pwd to do the
# job.  i wrote this function because i've seen systems that dont have
# this command.	
bash_realpath() {
	local input_path;
	input_path=$(sanitize_path "$1");
	if [ "$input_path" == / ]; then
		echo /;
		return 0;
	fi;
	local basename="${input_path##*/}";
	local dirname="${input_path%/*}";
	[ "$dirname" == "$input_path" ] && dirname=.;
	(
		cd -- "$dirname" || exit 1;
		printf %s\\n "$(pwd)/$basename";
	);
}


validate_drop_item_name() {
	local name=$1;
	case "$name" in
		# no technical reason to disallow square brackets but disallow
		# anyway.
		(""|.|..|"["|"]")
			return 1;
			;;
	esac;

	# slashes are disallowed.  we dont handle relatives paths for
	# destinations.
	local subst=${name//"/"/_};
	[ "$name" == "$subst" ] || return 1;

	return 0;
}

handle_incoming_files_and_dirs() {
	local header=$1; # the @@@@ line
	local is_local=$2; # 1 = file system. 0 = stdin.
	local dest_dropdir=$3;
	local dest_name=$4;
	local local_source_path=$5; # only provided for local source

	validate_drop_item_name "$dest_name" || {
		pipeline_panic "Invalid destination name '$dest_name'.";
	};

	# if this kernel doesn't need the object, send straigt to parent
	# without using the disk.

	if ! is_item_in_list "$dest_dropdir" "${localhost_dropdirs_names[@]}"; then
		# still make sure that parents actually need the object
		if is_item_in_list "$dest_dropdir" "${parents_dropdirs[@]}"; then

			if ((is_local)); then
				case "$header" in
					(@@@@file)
						testable id_2nufhu4hfui4 [ -f "$local_source_path" ] || {
							pipeline_coverage id_sduhiuregnjnf;
							pipeline_panic "The file '$local_source_path' doesn't exist or is not a file.";
						};

						echo "$header";
						dump_bin <<<"$dest_dropdir";
						dump_bin <<<"$dest_name";
						testable id_nfw3h4g8ih3498 gzip --stdout - < "$local_source_path" | dump_bin;
						pipestatus_save;
						if ! pipestatus_test 0; then
							pipeline_coverage id_fvh39nfgur;
							pipeline_panic "gzip exited with error.";
						fi;
						;;
					(@@@@dir)
						if ! (testable id_ndu93hg894hg cd -- "$local_source_path"); then
							pipeline_coverage id_xhiushutbdfudst;
							pipeline_panic "Could not change directory into '$local_source_path'.";
						fi;

						echo "$header";
						dump_bin <<<"$dest_dropdir";
						dump_bin <<<"$dest_name";
						(if cd -- "$local_source_path"; then testable id_asdfiehusgr tar -c -f - .; else echo ""; fi) | testable id_ahduh9g83h4g89hr gzip --stdout - | dump_bin;
						pipestatus_save;
						if ! pipestatus_test 0 || ! pipestatus_test 1; then
							pipeline_coverage id_asdh39nugh34gnur;
							pipeline_coverage id_uidhgiusng5rust;
							pipeline_panic "There was an error when archiving the directory '$local_source_path' with tar, or when compressing with gzip.";
						fi;
						;;
					(*)
						pipeline_panic "Unknown object '$header'.";
						;;
				esac;
			else
				echo "$header";
				dump_bin <<<"$dest_dropdir";
				dump_bin <<<"$dest_name";
				read_bin_pipe_dump_bin;
			fi;
			
		else
			if ! ((is_local)); then
				pipeline_coverage id__must_show_up___children_should_not_send_files_and_dirs_that_parents_dont_need;
				read_bin_pipe_dump_bin > /dev/null;
			fi;
		fi;
		return 0;
	fi;

	local temp_holder;
	temp_holder=$(mktemp) || {
		rm -f -- "$temp_holder";
		pipeline_panic "mktemp failed. Could not create temporary file to holde the file or directory that we are receiving.";
	};
	if ((is_local)); then
		case "$header" in
			(@@@@file)
				testable id_ncwuhgu4hrr94 cat -- "$local_source_path" | testable id_sdguiwhgu gzip --stdout - > "$temp_holder";
				pipestatus_save;
				if ! pipestatus_test 0; then
					rm -f "$temp_holder";
					pipeline_coverage id_gh9u3hg89rhrng493hrug;
					pipeline_panic "There was a problem with cat (for file '$local_source_path').";
				fi;
				if ! pipestatus_test 1; then
					rm -f "$temp_holder";
					pipeline_coverage id_asduiuf34fufhd9vng9h45guh;
					pipeline_panic "There was a problem with gzip (for file '$local_source_path').";
				fi;
				;;
			(@@@@dir)
				if ! (testable id_hgu9rhuh39u cd -- "$local_source_path"); then
					rm -f "$temp_holder";
					pipeline_coverage id_asbvui4gbfdbvuidbrgui;
					pipeline_panic "Could not change directory into '$local_source_path'.";
				fi;
				(if cd -- "$local_source_path"; then testable id_2h9vu3hr tar -c -f - .; else echo ""; fi) | testable id_v93uhrgv93 gzip --stdout - > "$temp_holder";
				pipestatus_save;
				if ! pipestatus_test 0 || ! pipestatus_test 1; then
					rm -f "$temp_holder";
					pipeline_coverage id_adnvrngi4u3huifhder;
					pipeline_coverage id_qjivudfh9u4n5guihg5;
					pipeline_panic "There was an error when archiving the directory '$local_source_path' with tar or when compressing with gzip.";
				fi;
				;;
			(*)
				rm -f "$temp_holder";
				pipeline_panic "Unknown object '$header'.";
				;;
		esac;
	else
		read_bin > "$temp_holder";
	fi;

	local i;
	for ((i = 0; i < ${#localhost_dropdirs_names[@]}; i++)); do
		if [ "${localhost_dropdirs_names[i]}" == "$dest_dropdir" ]; then
			(
				cd -- "${localhost_dropdirs_paths[i]}" || {
					rm -f "$temp_holder";
					pipeline_coverage id_bnuiergjn3uirfgi3ugr;
					pipeline_panic "Could not change directory into dropdir '${localhost_dropdirs_paths[i]}'.";
				};

				[ -f "$dest_name" ] || [ -d "$dest_name" ] && {
					rm -f "$temp_holder";
					pipeline_panic "There is already a file or directory called '$dest_name' in the drop directory '$dest_dropdir'.";
				};

				case "$header" in
					(@@@@file)
						testable id_vuherigrt gzip --stdout -d - < "$temp_holder" | testable id_anduierr tee -- "$dest_name" &> /dev/null;
						pipestatus_save;
						if ! pipestatus_test 0; then
							rm -f "$temp_holder";
							pipeline_coverage id_vnui3rhg9fhg398r;
							pipeline_panic "There was a problem with gzip (for files '$temp_holder' and '$dest_name').";
						fi;
						if ! pipestatus_test 1; then
							rm -f "$temp_holder";
							pipeline_coverage id_sntiun98hr3fb89;
							pipeline_panic "There was a problem with tee (for file '$dest_name').";
						fi;
						;;
					(@@@@dir)
						testable id_sgiuhrgur mkdir -- "$dest_name" || {
							rm -f "$temp_holder";
							pipeline_coverage id_ghuierhbunr9uhn3fnr;
							pipeline_panic "Could not create directory '$dest_name'.";
						};
						testable id_vhuiherg9ur cd -- "$dest_name" || {
							rm -f "$temp_holder";
							pipeline_coverage id_bnti9h3urhg9urh39g;
							pipeline_panic "Could not change directory into '$dest_name'.";
						};
						testable id_huvehrg gzip --stdout -d - < "$temp_holder" | testable id_ashdiuehr tar -x -f - .;
						pipestatus_save;
						if ! pipestatus_test 0; then
							rm -f "$temp_holder";
							pipeline_coverage id_bnieuhrgiu3huirbb3;
							pipeline_panic "There was a problem with gzip (for file '$temp_holder' for directory '$dest_name').";
						fi;
						if ! pipestatus_test 1; then
							rm -f "$temp_holder";
							pipeline_coverage id_msiiuf39uh938hgfj;
							pipeline_panic "There was a problem with tar (for directory '$dest_name').";
						fi;
						;;
				esac;

			) || return 1;
		fi;
	done;

	if ! ((is_root_kernel)); then
		# send to parent only if parent needs it.
		if is_item_in_list "$dest_dropdir" "${parents_dropdirs[@]}"; then
			echo "$header";
			dump_bin <<<"$dest_dropdir";
			dump_bin <<<"$dest_name";
			dump_bin < "$temp_holder";
		fi;
	fi;

	rm -f "$temp_holder";

}

handle_incoming_files_and_dirs_in_stream() {
	local line;
	while IFS="" read -r line || [ -n "$line" ]; do
		case "$line" in
			(@@@@file|@@@@dir)
				handle_incoming_files_and_dirs "$line" 0 "$(read_bin)" "$(read_bin)";
				;;
			(@@@*)
				echo "$line";
				read_bin_pipe_dump_bin;
				read_bin_pipe_dump_bin;
				;;
			(@@*)
				echo "$line";
				read_bin_pipe_dump_bin;
				;;
			(@*)
				echo "$line";
				;;			
			(*)
				# error "handle_incoming_files_and_dirs: Unknown message '$line'.  Panic.";
				echo @panic;
				;;
		esac;
	done;
}



# in a huge pipe line of many commands that communicate with our
# protocol by sending messages to their fd 1 (next command in pipe
# line) or fd 3, we must avoid the situation where multiple sections
# of the pipe line tries to write messages to fd 3 (our parent
# kernel).  multiple writes are not atomic, therefore the protocol
# breaks because it breaks the flow of @header followed by its
# arguments if an other command begins to write a message while the
# previous message is not completed.

# the easiest way to enforce protection of the protocol is that only
# one command in a pipe line is "priviledged" to write to fd 3, the
# others must write to their fd 1 or in temp files that can be managed
# at the appropriate time.  i dont want to "automate" the handling of
# fd 3 with lock files, it's probably asking for problems or risking a
# deadlock.

# THEREFORE generic_message_handler will be that priviledged function,
# so it goes at the end of a pipe line.

generic_message_handler() {
	# we cannot handle panic because we will always be inside a
	# subshell.  therefore we must forward the panic, which is also
	# our own panic mecanism for unknown message type.

	# the number of @ in general is the number of argments plus one,
	# so that a function like this one can yield back messages that it
	# doesn't support.

	local line;
	local subline;
	while IFS="" read -r line || [ -n "$line" ]; do
		# debug "GENERIC $rrssh_fork_depth: $line";
		case "$line" in
			(@@print_stdout)
				echocom @@print_stdout;
				read_bin_pipe_dump_bin 1>&3;
				;;
			(@@print_stderr)
				echocom @@print_stderr;
				read_bin_pipe_dump_bin 1>&3;
				;;
			(@panic)
				echo @panic;
				;;
			(@bliss)
				echo @bliss;
				;;
			(@@exitcode)
				echocom @@exitcode;
				read_bin_pipe_dump_bin 1>&3;
				;;
			(@@coverage)
				echocom @@coverage;
				read_bin_pipe_dump_bin 1>&3;
				;;
			(@epoll_panic)
				# this message should only be received from a
				# subkernel, therefore we have fd 6.
				if ((opt_stdin)); then
					echocom @epoll_panic;
					while IFS="" read -r subline || [ -n "$subline" ]; do
						case "$subline" in
							(@panic)
								echo @panic 1>&6;
								break;
								;;
							(@continue)
								echo @continue 1>&6;
								break;
								;;
							(*)
								error "Unknown message '$subline' received from parent. Panic.";
								echo @panic 1>&6;
								break;
								;;
						esac;
						break;
					done 0<&5;
				else
					echo @continue 1>&6;
				fi;
				;;
			(@@@@file|@@@@dir)
				if ! ((is_root_kernel)); then
					echocom "$line";
					read_bin_pipe_dump_bin 1>&3;
					read_bin_pipe_dump_bin 1>&3;
					read_bin_pipe_dump_bin 1>&3;
				else
					read_bin_pipe_dump_bin > /dev/null;
					read_bin_pipe_dump_bin > /dev/null;
					read_bin_pipe_dump_bin > /dev/null;
				fi;
				;;
			(@@child_dropdir)
				echo @@child_dropdir;
				read_bin_pipe_dump_bin;
				;;
			(@@@@*)
				echo "$line";
				read_bin_pipe_dump_bin;
				read_bin_pipe_dump_bin;
				read_bin_pipe_dump_bin;
				;;
			(@@@*)
				echo "$line";
				read_bin_pipe_dump_bin;
				read_bin_pipe_dump_bin;
				;;
			(@@*)
				echo "$line";
				read_bin_pipe_dump_bin;
				;;
			(@*)
				echo "$line";
				;;
			(*)
				error "generic_message_handler: Unknown message '$line'.  Panic.";
				echo @panic;
				;;
		esac;
	done;
}



# The "contract" with the command commands is as follow: They are
# responsible for shifting and consuming the toplevel_args because
# only they know how much arguments they consume.  They must respect
# the value of op_mode.  They can panic.  They must use their
# exit-code to indicate whether they must be considered successful or
# in error in regards to the operators and or not try.  They must only
# run (but always consume their arguments) if the main loop sets the
# variable indicating to do so.

# the main execution loop sets this when commands must read their
# arguments but skip their execution.  for example when running a
# "command chain".

skip_current_command_execution_flag=0;

current_command_must_run_p() {
	[ "$op_mode" == scan ] && return 1;
	((skip_current_command_execution_flag)) && return 1;
	return 0;
}

command_command() {
	local arg0;
	arg0=$(peek_toplevel_args);
	shift_toplevel_args;

	# command needs either a string for system() or [ ], so one argument obligatory.
	any_toplevel_args_remaining || {
		panic "The command 'command' must be provided with an argument.";
	};

	local arg1;
	arg1=$(peek_toplevel_args);
	local string_command="";
	local is_string=1;
	local argv=();
	local end_token="";

	if [ "$arg0" == --- ]; then
		is_string=0;
		end_token="---";
	else
		shift_toplevel_args;
		if [ "$arg1" == "[" ]; then
			is_string=0;
			end_token="]";
		else
			string_command=$arg1;
		fi;
	fi;
	
	local end_token_reached=0;
	if ! ((is_string)); then
		while any_toplevel_args_remaining; do
			if [ "$(peek_toplevel_args)" == "$end_token" ]; then
				end_token_reached=1;
				shift_toplevel_args;
				break;
			fi;
			argv+=("$(peek_toplevel_args)");
			shift_toplevel_args;
		done;

		((end_token_reached)) || {
			panic "The command 'command' must end with the corresponding ending token: '$end_token'.";
		};

		string_command="$(printf "%q " "${argv[@]}")";
		# debug "$string_command";
	fi;

	current_command_must_run_p || return 0;

	local rc=0;
	bash -c "$string_command" 0< /dev/null 3>&- 5>&- 6>&- 7>&- 2>&1 | send_to_stdout;
	rc=${PIPESTATUS[0]};
	wait;

	return "$rc";
}


command_fork() {
	local command_name;
	command_name=$(peek_toplevel_args);
	shift_toplevel_args;

	# TODO: if forking locally, then dont reprint all files, put a
	# reference to the first kernel on the current host.

	local is_host_command=0;
	local is_su_command=0;
	local is_scope_command=0;
	local is_sudo_prefix=0;

	case "$command_name" in
		(host)
			is_host_command=1;
			;;
		(sudo-host)
			is_host_command=1;
			is_sudo_prefix=1;
			;;
		(su)
			is_su_command=1;
			;;
		(sudo-su)
			is_su_command=1;
			is_sudo_prefix=1;
			;;
		("[")
			is_scope_command=1;
			;;
	esac;

	local arg_destination; # host commands
	local arg_username; # su commands
	local ssh_o_options=();
	local scope_opening_token="";
	local scope_closing_token="";
	if ! ((is_scope_command)); then
		arg_destination=$(peek_toplevel_args);
		arg_username=$(peek_toplevel_args);
		shift_toplevel_args;

		case "$command_name" in
			(host|sudo-host)
				while [ "$(peek_toplevel_args)" == -o ]; do
					shift_toplevel_args;
					any_toplevel_args_remaining || {
						panic "The -o option needs one argument.";
					};
					ssh_o_options+=(-o "$(peek_toplevel_args)");
					shift_toplevel_args;
				done;
				;;
		esac;

		scope_opening_token=$(peek_toplevel_args);
		case "$scope_opening_token" in
			("[")
				scope_closing_token="]";
				;;
			(":")
				scope_closing_token=$toplevel_scope_closing_token;
				;;
			(*)
				panic "The '$command_name' command must begin with an opening '[' or ':'.";
				;;
		esac;
	    shift_toplevel_args;
	else
		scope_opening_token="[";
		scope_closing_token="]";
	fi;

	# at this point, the opening square bracket or : is consumed, the
	# next toplevel arg is the first token inside the scope.  the
	# closing square bracket will come later and may be consumed by
	# the sub kernel.

	# pre-execution analysis
	local total_scope_args_shift=0;
	# local total_scope_args_shift_provided=0;
	local sub_analyser_bliss=0;

	local analysis_output;
	analysis_output=$(mktemp) || {
		panic "mktemp failed";
	};

	local sub_extra_options=(
		-x @@toplevel_scope_closing_token -x "$scope_closing_token"

		--recycling_base_toplevel_skip
		"$((recycling_base_toplevel_skip + total_toplevel_args_shift_count))"
	);
	if ! [ "$scope_opening_token" == ":" ]; then
		sub_extra_options+=(
			-x @consume_toplevel_scope_closing_token
		);
	fi;
	if ((is_scope_command)); then
		sub_extra_options+=(
			-x @@rrssh_host_depth
			-x "$rrssh_host_depth"
		);
	else
		sub_extra_options+=(
			-x @@rrssh_host_depth
			-x "$((rrssh_host_depth + 1))"
		);
	fi;

	bash "$KERNEL_PATH" -- --mode scan --recycled "${sub_extra_options[@]}" | generic_message_handler > "$analysis_output";

	local line;
	local child_dropdir;
	local subkernel_child_dropdirs=();
	# shellcheck disable=SC2094
	while IFS="" read -r line || [ -n "$line" ]; do
		case "$line" in
			(@@total_toplevel_shift)
				# total_scope_args_shift_provided=1;
				total_scope_args_shift=$(read_bin);
				;;
			(@bliss)
				sub_analyser_bliss=1;
				;;
			(@panic)
				# shellcheck disable=SC2094
				rm -f "$analysis_output";
				panic "Sub kernel panicked during analysis.";
				;;
			(@kernel_start)
				true;
				;;
			(@@child_dropdir)
				child_dropdir=$(read_bin);
				subkernel_child_dropdirs+=("$child_dropdir");
				if [ "$op_mode" == scan ]; then
					echocom @@child_dropdir;
					dump_bin <<<"$child_dropdir" 1>&3;
				fi;
				;;
			(*)
				# shellcheck disable=SC2094
				rm -f "$analysis_output";
				panic "Unknown message during scope analysis: '$line'.";
				;;
		esac;
	done < "$analysis_output";
	rm -f "$analysis_output";
	((sub_analyser_bliss)) ||
		panic "Sub scope analyser did not end blissfully.";

	current_command_must_run_p || {
	    shift_toplevel_args "$total_scope_args_shift";
		return 0;
	};



	local subkernel_stdin;
	subkernel_stdin=$(mktemp_fifo) || {
		panic "mktemp_fifo failed";
	};
	local subkernel_stdout;
	subkernel_stdout=$(mktemp_fifo) || {
		rm -f -- "$subkernel_stdin";
		panic "mktemp_fifo failed";
	};

	(
		exec 3>&- 5>&-;

		print_landing_script() {

			# the landing script should always exit 0 if it
			# successfully runs the kernel, so that we know from the
			# exit code whether the ssh/su command or the landing
			# failed.

			local call_args=("$@");
			cat <<LANDING_SCRIPT;
echo @landing_start;

call_args=($(printf "%q " "${call_args[@]}"));
make_command_fail_ids=($(printf "%q " "${make_command_fail_ids[@]}"));
LANDING_SCRIPT

			declare -f dump_bin;
			declare -f read_line;
			declare -f read_bin;
			declare -f read_bin_pipe_dump_bin;
			declare -f testable;
			declare -f pipeline_coverage;

			cat <<"LANDING_SCRIPT";

send_to_stderr() {
	echo @@print_stderr;
	dump_bin;
}
send_to_landing_err() {
	echo @@print_landing_err;
	dump_bin;
}
printferr() {
	printf "$@" | send_to_stderr;
}
printf_landing_err() {
	printf "$@" | send_to_landing_err;
}
error() {
	printferr "ERROR: %s ERROR\n" "$@";
}
debug() {
	printferr "DEBUG: %s DEBUG\n" "$@";
}

coverage() {
	pipeline_coverage "$@";
}




kernel_file_path=$(testable id_nuirhienvfh mktemp) || {
	coverage id_adsuhidfuvnri;
	printf_landing_err "mktemp failed.  Could not create a temporary file for the sub kernel.";
	exit 1;
};

read_bin | testable id_fdhv9qh5gf tee "$kernel_file_path" &> /dev/null || {
	coverage id_fhiuashfiuhr;
	printf_landing_err "tee failed.  Could not dump contents to the temporary file meant to hold the sub kernel."
	rm -f "$kernel_file_path";
	exit 1;
};

# we receive the heavy objects separetaly so that they are not
# uselessly encoded through base64 2 times, which would further their
# transmission size on a network.

line="";
while IFS="" read -r line || [ -n "$line" ]; do
	case "$line" in
		(@eof)
			echo @eof >> "$kernel_file_path";
			break;
			;;
		(@@@@file|@@@@dir)
			echo "$line" >> "$kernel_file_path";
			read_bin_pipe_dump_bin >> "$kernel_file_path";
			read_bin_pipe_dump_bin >> "$kernel_file_path";
			read_bin_pipe_dump_bin >> "$kernel_file_path";
			;;
		(@@coverage)
			echo @@coverage >> "$kernel_file_path";
			read_bin_pipe_dump_bin >> "$kernel_file_path";
			;;
		(@@print_stdout|@@print_stderr)
			echo "$line";
			read_bin_pipe_dump_bin;
			;;
		(@panic)
			echo @panic >> "$kernel_file_path";
			break;
			;;
		(*)
			error "Unknown message '$line' received in stdin during duplication.";
			rm -f "$kernel_file_path";
			exit 1;
			;;
	esac;
done;


testable id_asudhfisuh bash "$kernel_file_path" -- "${call_args[@]}";
rm -f "$kernel_file_path";
exit 0;

LANDING_SCRIPT

		}

		cmd=();
		if ((is_sudo_prefix)); then
			cmd+=(sudo);
		fi;
		if ((is_host_command)); then
			# cmd+=(ssh -o ConnectTimeout=10 -o ServerAliveInterval=15 -o ServerAliveCountMax=3 -- "$arg_destination");
			cmd+=(ssh -o ConnectTimeout=10 -o ServerAliveInterval=15 "${ssh_o_options[@]}" -- "$arg_destination");
		elif ((is_su_command)); then
			if ! ((opt_fake_su)); then
				cmd+=(su - -- "$arg_username" -c);
			else
				cmd+=(bash -c);
			fi;
		elif ((is_scope_command)); then
			cmd+=(bash -c);
		fi;

		"${cmd[@]}" "bash -c $(printf %q "$(print_landing_script --mode run --stdin)")";
		fork_command_rc=$?;

		echo @@fork_command_rc;
		dump_bin <<<"$fork_command_rc";

	) 0< "$subkernel_stdin" 1> "$subkernel_stdout" &
	exec 6> "$subkernel_stdin" 7< "$subkernel_stdout";


	(
		(
			begin_basic_fork;



			echo @@toplevel_scope_closing_token;
			dump_bin <<<"$scope_closing_token";
			if ! [ "$scope_opening_token" == ":" ]; then
				echo @consume_toplevel_scope_closing_token;
			fi;

			echo @@rrssh_host_depth;
			if ((is_scope_command)); then
				dump_bin <<<"$rrssh_host_depth";
			else
				dump_bin <<<$((rrssh_host_depth + 1));
			fi;


			pipeline_coverage id_g39rgr9ghf39h38;


			# for optimization of transfers over the network, we send all
			# dirnames that we need and that our parents need.
			for dropdir_name in "${parents_dropdirs[@]}"; do
				echo @@parent_dropdir;
				dump_bin <<<"$dropdir_name";
			done;
			if ! ((is_scope_command)); then
				for dropdir_name in "${localhost_dropdirs_names[@]}"; do
					echo @@parent_dropdir;
					dump_bin <<<"$dropdir_name";
				done;
			else
				echo @@heavy_objects_kernel_path;
				dump_bin <<<"$HEAVY_OBJECTS_KERNEL_PATH";

				for ((i = 0; i < ${#localhost_dropdirs_names[@]}; i++)); do
					echo @@@add_dropdir;
					dump_bin <<<"${localhost_dropdirs_names[i]}";
					dump_bin <<<"${localhost_dropdirs_paths[i]}";
				done;
				for ((i = 0; i < ${#localhost_taken_types[@]}; i++)); do
					echo @@@@@take_obj;
					dump_bin <<<"${localhost_taken_dest_dropdirs[i]}";
					dump_bin <<<"${localhost_taken_types[i]}";
					dump_bin <<<"${localhost_taken_dest_names[i]}";
					dump_bin <<<"${localhost_taken_source_paths[i]}";
				done;
			fi;

			echo @end_of_header;

		) | dump_bin;

		pipeline_coverage id_sng93uhrgr3duv;

		if ! ((is_scope_command)); then
			for ((i = 0; i < ${#localhost_taken_types[@]}; i++)); do
				is_item_in_list "${localhost_taken_dest_dropdirs[i]}" "${subkernel_child_dropdirs[@]}" ||
					continue;
				case "${localhost_taken_types[i]}" in
					(f)
						[ -f "${localhost_taken_source_paths[i]}" ] || {
							pipeline_coverage id_i304gjvfuh938rh93hr;
							pipeline_panic "The file '${localhost_taken_source_paths[i]}' disapeared.";
						};

						echo @@@@file;
						dump_bin <<<"${localhost_taken_dest_dropdirs[i]}";
						dump_bin <<<"${localhost_taken_dest_names[i]}";
						testable id_sdghuiarhui gzip --stdout - < "${localhost_taken_source_paths[i]}" | dump_bin;
						pipestatus_save;
						if ! pipestatus_test 0; then
							pipeline_coverage id_vneuhg894hgrneg9u3h;
							pipeline_panic "There was a problem with gzip for the file '${localhost_taken_source_paths[i]}'.";
						fi;
						;;
					(d)
						[ -d "${localhost_taken_source_paths[i]}" ] || {
							pipeline_coverage id_uiwhefh938hvnu39h93;
							pipeline_panic "Th directory '${localhost_taken_source_paths[i]}' disapeared.";
						};

						(
							testable id_asudhiauhieruger cd -- "${localhost_taken_source_paths[i]}" || {
								pipeline_coverage id_fuvishugirgnd;
								pipeline_panic "Could not change directory into directory '${localhost_taken_source_paths[i]}.";
							};

							echo @@@@dir;
							dump_bin <<<"${localhost_taken_dest_dropdirs[i]}";
							dump_bin <<<"${localhost_taken_dest_names[i]}";

							testable id_asudhfiuhred tar -c -f - . | testable id_308hgue3u gzip --stdout - | dump_bin;
							pipestatus_save;
							if ! pipestatus_test 0 || ! pipestatus_test 1; then
								pipeline_coverage id_uejr8gh398hfhg93;
								pipeline_coverage id_n98rhg9r3h93g7h;
								pipeline_panic "There was a problem when archiving directory '${localhost_taken_source_paths[i]}' with tar, or while compressing with gzip.";
							fi;

						) || exit 1;
						;;
				esac;
			done;

			testable id_shdgiuehrs [ -f "$HEAVY_OBJECTS_KERNEL_PATH" ] || {
				pipeline_coverage id_ionrgr93hfv93uhr9;
				pipeline_panic "The kernel file at '$HEAVY_OBJECTS_KERNEL_PATH' disapeared.";
			};

			{
				skip_kernel;
				skip_to_heavy_objects;
				while IFS="" read -r line || [ -n "$line" ]; do
					case "$line" in
						(@@coverage)
							read_bin_pipe_dump_bin > /dev/null;
							;;
						(@@@@file|@@@@dir)
							obj_dest_dropdir=$(read_bin);
							if is_item_in_list "$obj_dest_dropdir" "${subkernel_child_dropdirs[@]}"; then
								echo "$line";
								dump_bin <<<"$obj_dest_dropdir";
								read_bin_pipe_dump_bin;
								read_bin_pipe_dump_bin;
							else
								read_bin_pipe_dump_bin > /dev/null;
								read_bin_pipe_dump_bin > /dev/null;
							fi;
							;;
						(@eof)
							break;
							;;
						(*)
							pipeline_panic "Unknown message '$line' when reading kernel for files and dirs to forward.";
							;;
					esac;
				done;
			} < "$HEAVY_OBJECTS_KERNEL_PATH";
		fi;


		echo @eof;

	) 1>&6;


	local temp_com_file;
	temp_com_file=$(mktemp) || {
		rm -f -- "$subkernel_stdin";
		rm -f -- "$subkernel_stdout";
		panic "mktemp failed";
	};
	(

		# we handle file/folder transfers and other things here so
		# that it happens simultaneously accross all hosts, and thus
		# faster than one host at a time.  however we are in a
		# subshell.  temp_com_file is for information that must be
		# kept outside the subshell.

		handle_incoming_files_and_dirs_in_stream;

	) 0<&7 | (

		generic_message_handler;

	) > "$temp_com_file";

	exec 6>&- 7>&-;
	rm -f -- "$subkernel_stdin";
	rm -f -- "$subkernel_stdout";

	# the landing process has its own "stream" of error messages other
	# than "stdout" "stderr" so that we catch and print these messages
	# only if rrssh was not provided the option to not panic on failed
	# ssh/su.
	local landing_msgs=(); # all errors.  the landing does not print any happy messages.
	local landing_failed=0;

	local bliss_received=0;
	local ignore_missing_bliss=0;
	local must_panic=0;
	local execution_total_args_shift=0;
	local scope_exitcode_received=0;
	local scope_exitcode=0;
	local fork_command_rc_received=0;
	local fork_command_rc=0;
	local landing_start_received=0;
	local kernel_start_received=0;
	while IFS="" read -r line || [ -n "$line" ]; do
		case "$line" in
			(@panic)
				must_panic=1;
				break;
				;;
			(@bliss)
				bliss_received=1;
				;;
			(@@total_toplevel_shift)
				execution_total_args_shift=$(read_bin);
				;;
			(@@scope_exitcode)
				scope_exitcode_received=1;
				scope_exitcode=$(read_bin);
				;;
			(@@fork_command_rc)
				fork_command_rc_received=1;
				fork_command_rc=$(read_bin);
				;;
			(@landing_start)
				landing_start_received=1;
				;;
			(@kernel_start)
				kernel_start_received=1;
				;;
			(@@print_landing_err)
				landing_msgs+=("$(read_bin)");
				;;
			(*)
				error "Unknown message received from sub kernel result parsing code: '$line'.";
				must_panic=1;
				break;
				;;
		esac;
	done < "$temp_com_file";
	rm -f "$temp_com_file";

	if ((must_panic)); then
		panic "Triggering a panic.";
	fi;

	if ((fork_command_rc_received)) && ! ((fork_command_rc == 0)); then

		# whether we received @landing_start is the difference between
		# a failing ssh/su VS the landing script that exited non-0
		# voluntarily.

		landing_failed=1;

		coverage id_i92idnvu93h9u7ndf924;

		if ((landing_start_received)); then
			if ((kernel_start_received)); then
				landing_msgs+=(
					"The ssh or su command succeeded and the sub-kernel started, but something happened."
				);
			else
				landing_msgs+=(
					"The ssh or su command succeeded, but the sub-kernel could not be started during duplication."
				);
			fi;
		else
			landing_msgs+=(
				"The ssh or su command seems to fail."
				"Is an ssh key missing?"
				"Is ssh, su, or sudo prompting for a password?"
				"Is the destination resolving and reachable?"
				"Is there any spelling mistake?"
			);
		fi;
	elif ! ((landing_start_received)); then
		coverage id_fh9u3ghru9hunnc29uur;
		landing_failed=1;
		landing_msgs+=(
			"The ssh or su command seems to fail."
			"Is an ssh key missing?"
			"Is ssh, su, or sudo prompting for a password?"
			"Is the destination resolving and reachable?"
			"Is there any spelling mistake?"
		);
	elif ! ((kernel_start_received)); then
		coverage id_39rgh39rghurg3hrgur;
		landing_failed=1;
		landing_msgs+=(
			"The ssh or su command succeeded, but the kernel failed to start."
		);
	fi;

	if ((landing_failed)); then
		if ! ((opt_i)); then
			coverage id_u9fh3r9uhg9urfw;
			panic "${landing_msgs[@]}";
		else
			coverage id_n9vu3rhgjisfj9r3;

			# MAYBE TODO: maybe we should still panic if we are a
			# simple scope and not a host or su command.

			ignore_missing_bliss=1;
			# instead of panicking, we behave like a scope that exited non-0.
			scope_exitcode_received=1;
			scope_exitcode=1;
		fi;
	fi;

	[ "$execution_total_args_shift" == "$total_scope_args_shift" ] || {
		coverage id_2ifhu347bsdgh7u;

		# if the sub scope did not end because of a non-0 command, it
		# is normal that execution did not consume as many arguments
		# as pre-execution analysis.

		if ((scope_exitcode == 0)); then
			panic "The amount of token consumed during scope analysis is not equal as when executed.  scan: $total_scope_args_shift. execution: $execution_total_args_shift. bliss: $bliss_received. ";
		fi;
	};
	shift_toplevel_args "$total_scope_args_shift";

	if ! ((bliss_received)) && ! ((ignore_missing_bliss)); then
		panic "Sub kernel at remote host did not end blissfully.";
	fi;

	if ((scope_exitcode_received)); then
		coverage id_snjdn92hguehu;
		return "$scope_exitcode";
	fi;

}

command_make_command_fail() {
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command 'make-command-fail' needs 1 argument.";
	};

	local id;
	id=$(peek_toplevel_args);
	shift_toplevel_args;

	current_command_must_run_p || return 0;

	make_command_fail_ids+=("$id");
}


command_cd() {
	local arg0;
	arg0=$(peek_toplevel_args);
	shift_toplevel_args;

	local path;
	case "$arg0" in
		(cd|pushd)
			any_toplevel_args_remaining || {
				panic "The command '$arg0' needs 1 argument.";
			};
			path=$(peek_toplevel_args);
			shift_toplevel_args;
			;;
	esac;

	current_command_must_run_p || return 0;

	case "$arg0" in
		(cd)
			cd -- "$path" || {
				error "Could not cd to '$path'.";
				return 1;
			};
			return 0;
			;;
		(home)
			cd || {
				error "Could not cd to home directory.";
				return 1;
			};
			return 0;
			;;
		(pushd)
			pushd -- "$path" || {
				error "Could not pushd to '$path'.";
				return 1;
			};
			return 0;
			;;
		(popd)
			popd || {
				error "Could not popd.";
				return 1;
			};
			return 0;
			;;
	esac;

}



command_drop_dir() {
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command 'drop-dir' needs 2 arguments.";
	};
	local dropdir_name;
	dropdir_name=$(peek_toplevel_args);
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command 'drop-dir' needs 2 arguments.";
	};
	local dropdir_path;
	dropdir_path=$(peek_toplevel_args);
	shift_toplevel_args;

	if [ "$op_mode" == scan ]; then
		echocom @@child_dropdir;
		dump_bin <<<"$dropdir_name" 1>&3;
	fi;

	current_command_must_run_p || return 0;


	if ! [ -d "$dropdir_path" ]; then
		mkdir -- "$dropdir_path" || {
			coverage id_nv93hrg98h983rh;
			panic "Could not create drop directory '$dropdir_name' at location '$dropdir_path'.  Do we have permission?  Does the parent directory exist?";
		};
	fi;

	local absolute_path;
	absolute_path=$(testable id_nv39ru9uh3 cd -- "$dropdir_path" && pwd) || {
		coverage id_nef9uj29gh839hgr;
		panic "Could not change the current directory to the drop directory '$dropdir_name' at location '$dropdir_path'.  Do we have access?";
	};

	localhost_dropdirs_names+=("$dropdir_name");
	localhost_dropdirs_paths+=("$absolute_path");


	local line;
	local current_obj_dest_dropdir;
	local current_obj_dest_name;

	local i;
	for ((i = 0; i < ${#localhost_taken_types[@]}; i++)); do
		[ "$dropdir_name" == "${localhost_taken_dest_dropdirs[i]}" ] ||
			continue;
		current_obj_dest_name=${localhost_taken_dest_names[i]};
		case "${localhost_taken_types[i]}" in
			(f)
				[ -f "$absolute_path/$current_obj_dest_name" ] && {
					coverage id_sdowrgu3nrg3u9;
					panic "The file '$absolute_path/$current_obj_dest_name' already exists.";
				};
				[ -d "$absolute_path/$current_obj_dest_name" ] && {
					coverage id_dnv9uhr9u3h3u;
					panic "Cannot overwrite a directory with a file. At '$absolute_path/$current_obj_dest_name'.";
				};
				testable id_asdguier cp -- "${localhost_taken_source_paths[i]}" "$absolute_path/$current_obj_dest_name" || {
					coverage id_n9284ghu34hdh984h;
					panic "The cp command ended in error.";
				};
				;;
			(d)
				[ -d "$absolute_path/$current_obj_dest_name" ] && {
					coverage id_29fhihg934hhg98u;
					panic "The directory '$absolute_path/$current_obj_dest_name' already exists.";
				};
				[ -f "$absolute_path/$current_obj_dest_name" ] && {
					coverage id_io2ef284hguihguih4;
					panic "Cannot overwrite a file with a directory. At '$absolute_path/$current_obj_dest_name'.";
				};
				testable id_vh9u3rnv39u cp -r -- "${localhost_taken_source_paths[i]}" "$absolute_path/$current_obj_dest_name" || {
					coverage id_jf2ifj849he984ugh9u34;
					panic "The cp -r command ended in error.";
				};
				;;
		esac;
	done;

	{
		skip_kernel;
		skip_to_heavy_objects;

		while IFS="" read -r line || [ -n "$line" ]; do
			case "$line" in
				(@@coverage)
					read_bin_pipe_dump_bin > /dev/null;
					;;
				(@@@@file)
					current_obj_dest_dropdir=$(read_bin);
					current_obj_dest_name=$(read_bin);
					if [ "$current_obj_dest_dropdir" == "$dropdir_name" ]; then
						[ -f "$absolute_path/$current_obj_dest_name" ] && {
							coverage id_wuifhiuhgb3hbrgui3h;
							panic "Cannot receive file because a file '$absolute_path/$current_obj_dest_name' already exists.";
						};
						[ -d "$absolute_path/$current_obj_dest_name" ] && {
							panic "Cannot receive file because a directory '$absolute_path/$current_obj_dest_name' exists.";
						};
						touch -- "$absolute_path/$current_obj_dest_name" || {
							panic "Could not create file: '$absolute_path/$current_obj_dest_name'.";
						};
						read_bin | testable id_cn3rh39u3g gzip --stdout -d - > "$absolute_path/$current_obj_dest_name" || {
							coverage id_nef29h4g984hgurhsg94;
							panic "There was a problem with gzip while writing to '$absolute_path/$current_obj_dest_name'.";
						};
					else
						read_bin_pipe_dump_bin > /dev/null;
					fi;
					;;
				(@@@@dir)
					current_obj_dest_dropdir=$(read_bin);
					current_obj_dest_name=$(read_bin);
					if [ "$current_obj_dest_dropdir" == "$dropdir_name" ]; then
						[ -f "$absolute_path/$current_obj_dest_name" ] && {
							coverage id_2fo2huf9uhf9u3h;
							panic "Cannot receive directory because a file '$absolute_path/$current_obj_dest_name' exists.";
						};
						[ -d "$absolute_path/$current_obj_dest_name" ] && {
							coverage id_dni3g9hguu934h4;
							panic "Cannot receive directory because a directory '$absolute_path/$current_obj_dest_name' already exists.";
						};
						testable id_nv20h49gh3un mkdir -- "$absolute_path/$current_obj_dest_name" || {
							coverage id_nd3uru93hg984h;
							panic "Could not create directory '$absolute_path/$current_obj_dest_name'.";
						};
						(
							testable id_vj39hgu34 cd -- "$absolute_path/$current_obj_dest_name" || {
								coverage id_nv39uhg894hg938;
								panic "Could not change directory into '$absolute_path/$current_obj_dest_name'";
							};

							read_bin | testable id_nc92h4u gzip --stdout -d - | testable id_n08h4fu3 tar -x -f - .;
							pipestatus_save;
							if ! pipestatus_test 1 || ! pipestatus_test 2; then
								coverage id_n29h92h4hh489hg;
								coverage id_nvu3hg984h;
								panic "There was a problem with gzip, or while extracting with tar (for directory '$absolute_path/$current_obj_dest_name').";
							fi;
						) || exit 1;
					else
						read_bin_pipe_dump_bin > /dev/null;
					fi;
					;;
				(@eof)
					break;
					;;
				(*)
					panic "Unknown object '$line' in kernel.";
					;;
			esac;
		done;

	} < "$HEAVY_OBJECTS_KERNEL_PATH";

}




command_take() {
	local arg0;
	arg0=$(peek_toplevel_args);
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command take needs 3 arguments.";
	};
	local obj_path;
	obj_path=$(peek_toplevel_args);
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command take needs 3 arguments.";
	};
	local dest_name;
	dest_name=$(peek_toplevel_args);
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command take needs 3 arguments.";
	};
	local dest_dropdir;
	dest_dropdir=$(peek_toplevel_args);
	shift_toplevel_args;



	[ -n "$obj_path" ] || {
		panic "The source path for the $arg0 command cannot be an empty string.";
	};
	if [ -z "$dest_name" ]; then
		if [ "$arg0" == take-dir ]; then
			case "$(basename -- "$obj_path")" in
				(.|..)
					panic "When calling take-dir with a source directory named '.' or '..', you must provide a destination name.";
					;;
			esac;
		fi;
		dest_name=$(basename -- "$obj_path");
	fi;
	validate_drop_item_name "$dest_name" || {
		panic "Invalid destination name '$dest_name'.";
	};

	current_command_must_run_p || return 0;


	local header_line="";
    case "$arg0" in
		(take-file)
			header_line=@@@@file;
			[ -f "$obj_path" ] || {
				panic "The file '$obj_path' doesn't exist or is not a file.";
			};
			# debug "$(bash_realpath "$obj_path")";
			localhost_taken_types+=("f");
			localhost_taken_dest_dropdirs+=("$dest_dropdir");
			localhost_taken_dest_names+=("$dest_name");
			localhost_taken_source_paths+=("$(bash_realpath "$obj_path")");
			;;
		(take-dir)
			header_line=@@@@dir;
			[ -d "$obj_path" ] || {
				panic "The directory '$obj_path' doesn't exist or is not a directory.";
			};
			# debug "$(bash_realpath "$obj_path")";
			localhost_taken_types+=("d");
			localhost_taken_dest_dropdirs+=("$dest_dropdir");
			localhost_taken_dest_names+=("$dest_name");
			localhost_taken_source_paths+=("$(bash_realpath "$obj_path")");
			;;
	esac;

	local temp_messages;
	temp_messages=$(mktemp) || {
		panic "mktemp failed";
	};
	(
	    handle_incoming_files_and_dirs "$header_line" 1 "$dest_dropdir" "$dest_name" "$obj_path";
	) | generic_message_handler > "$temp_messages";

	local line;
	# shellcheck disable=SC2094
	{
		while IFS="" read -r line || [ -n "$line" ]; do
			case "$line" in
				(@panic)
					# shellcheck disable=SC2094
					rm -f "$temp_messages";
					panic "handle_incoming_files_and_dirs or generic_message_handler indicated to panic.";
					;;
				(*)
					# shellcheck disable=SC2094
					rm -f "$temp_messages";
					panic "Unknown message '$line' while reading the output of handle_incoming_files_and_dirs.";
					;;
			esac;
		done;
	} < "$temp_messages";

	rm -f "$temp_messages";
}

command_print() {
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command print needs 1 argument.";
	};
	local message;
	message=$(peek_toplevel_args);
	shift_toplevel_args;

	current_command_must_run_p || return 0;

	printfout '%s\n' "$message";
}

command_panic() {
	shift_toplevel_args;

	any_toplevel_args_remaining || {
		panic "The command print needs 1 argument.";
	};
	local message;
	message=$(peek_toplevel_args);
	shift_toplevel_args;

	current_command_must_run_p || return 0;

	panic "User triggered panic:" "$message";
}


if false; then
	coverage id__if_this_one_shows_up__then_coverage_detection_works;
fi;
if true && ! ((is_root_kernel)); then
	coverage id__if_this_one_shows_up__then_coverage_detection_doesnt_work;
fi;

main_execution_loop() {

	coverage id_dsfhiudvhsdfg;

	local current_toplevel_command;
	local current_command_rc=0;
	local current_command_reverse_rc=0;
	local current_chain_rc=0;
	local is_first_command_of_chain=1;
	local current_chain_has_try_prefix=0;
	local scope_closing_token_reached=0;
	local operator_used=0;

	skip_current_command_execution_flag=0;
	while any_toplevel_args_remaining; do
		current_command_rc=0;
		current_command_reverse_rc=0;
		operator_used=0;

		epoll_panic && {
			panic "epoll_panic indicated to panic.";
		};

		if [ -n "$toplevel_scope_closing_token" ]; then
			if ((is_first_command_of_chain)); then
				if [ "$(peek_toplevel_args)" == "$toplevel_scope_closing_token" ]; then
					scope_closing_token_reached=1;
					if ((consume_toplevel_scope_closing_token)); then
						shift_toplevel_args;
					fi;
					break;
				fi;
			fi;
		fi;

		if ((is_first_command_of_chain)); then
			if [ "$(peek_toplevel_args)" == try ]; then
				current_chain_has_try_prefix=1;
				shift_toplevel_args;
			fi;
		fi;

		if any_toplevel_args_remaining && [ "$(peek_toplevel_args)" == not ]; then
			current_command_reverse_rc=1;
			shift_toplevel_args;
		fi;

		if ! any_toplevel_args_remaining; then
			panic "An rrssh command must be provided after a prefix operator.";
		fi;
		current_toplevel_command=$(peek_toplevel_args);

		case "$current_toplevel_command" in
			(command|---)
				command_command;
				current_command_rc=$?;
				;;
			(host|sudo-host|su|sudo-su|"[")
				command_fork;
				current_command_rc=$?;
				;;
			(make-command-fail)
				command_make_command_fail;
				current_command_rc=$?;
				;;
			(true)
				shift_toplevel_args;
				current_command_rc=0;
				;;
			(false)
				shift_toplevel_args;
				current_command_rc=1;
				;;
			(cd|home|pushd|popd)
				command_cd;
				current_command_rc=$?;
				;;
			(drop-dir)
				command_drop_dir;
				current_command_rc=$?;
				;;
			(take-file|take-dir)
				command_take;
				current_command_rc=$?;
				;;
			(print)
				command_print;
				current_command_rc=$?;
				;;
			(panic)
				command_panic;
				current_command_rc=$?;
				;;
			(debug)
				shift_toplevel_args;
				if current_command_must_run_p; then
					echoout "ASDF";
				fi;
				;;
			(delim)
				shift_toplevel_args;
				if current_command_must_run_p; then
					echoout "==== ($rrssh_fork_depth $(hostname))";
				fi;
				;;
			(pwd)
				shift_toplevel_args;
				if current_command_must_run_p; then
					pwd | send_to_stdout;
				fi;
				;;
			(*)
				echocom @@exitcode;
				dump_bin <<<"1" 1>&3;
				panic "Invalid rrssh command: '$current_toplevel_command'.";
				;;
		esac;

		epoll_panic && {
			panic "epoll_panic indicated to panic.";
		};

		is_first_command_of_chain=0;
		if ((current_command_reverse_rc)); then
			current_command_rc=$((! current_command_rc));
		fi;

		# if the command had to run, its return code is now the
		# current return code of the command chain.
		if current_command_must_run_p; then
			current_chain_rc=$current_command_rc;
		fi;

		if any_toplevel_args_remaining; then
			case "$(peek_toplevel_args)" in
				(and)
					operator_used=1;
					skip_current_command_execution_flag=$current_chain_rc;
					;;
				(or)
					operator_used=1;
					skip_current_command_execution_flag=$((! current_chain_rc));
					;;
			esac;
			if ((operator_used)); then
				shift_toplevel_args;
				if ! any_toplevel_args_remaining; then
					panic "An rrssh command must be provided after an infix operator.";
				fi;
				continue;
			fi;
		fi;

		# when execution reaches here, we have completed a complete "command chain"
		if ! ((current_chain_has_try_prefix)) && ! ((current_chain_rc == 0)); then
			if ((opt_p)) || ((is_root_kernel)); then
				echocom @@exitcode;
				dump_bin <<<"$current_chain_rc" 1>&3;
				# TODO: add command chain and line number to error message
				panic "The command chain exited non-0.";
			else
				echocom @@scope_exitcode;
				dump_bin <<<"$current_chain_rc" 1>&3;

				# we need to stop execution early and return to the
				# body of main() so that we echocom @bliss to indicate
				# we terminated properly, however we have to skip the
				# code that ensures that the while loop terminated
				# before we reached an ending token.

				# break;
				return 1;

			fi;
		fi;

		# now we reset flags for the next "command chain".
		is_first_command_of_chain=1;
		skip_current_command_execution_flag=0;
		current_chain_has_try_prefix=0;
		current_chain_rc=0;

	done;

	if ! ((is_root_kernel)); then
		if ! ((scope_closing_token_reached)); then
			# an empty string means we had to read tokens until the
			# end.
			if [ -n "$toplevel_scope_closing_token" ]; then
				panic "The scope must end with a closing token $toplevel_scope_closing_token";
			fi;
		fi;
	fi;

}


main_kernel_inner_function() {

	"${kernel_inner_function_args[@]}" |& send_to_stdout;
	pipestatus_save;

	echocom @@exitcode;
	dump_bin <<<"$(pipestatus_check 0)" 1>&3;

}

main() {
	load_eof_values;

	if ((opt_recycled)); then
		shift_toplevel_args "$recycling_base_toplevel_skip";
		total_toplevel_args_shift_count=0;
	fi;

	case "$op_mode" in
		(kernel-inner-function)
		    main_kernel_inner_function;
			;;
		(*)
			main_execution_loop;

			if ! ((is_root_kernel)); then
				echocom @@total_toplevel_shift;
				dump_bin <<<"$total_toplevel_args_shift_count" 1>&3;
			fi;
			;;
	esac;

	echocom @bliss;
}

main;
exit "$?";

KERNEL
	
}




# THE script to be executed.
toplevel_commands=();
toplevel_commands_provided=0;

kernel_inner_function_args=();

read_toplevel_commands_from_file() {
	local filepath=$1;
	local current_line_number=1;
	local output_file;
	output_file=$(mktemp);
	local temp_script_path;
	local line;
	local word;
	local parsed_word;
	while IFS="" read -r line || [ -n "$line" ]; do
		temp_script_path=$(mktemp);
		{
			# printf %q ensure that all arguments are only one line
			# when printed.
			cat <<"SCRIPT";
				print_args() {
					(($# > 0)) && printf %q\\n "$@";
					exit 0;
				}
SCRIPT
			printf %s\\n "print_args $line";
		} > "$temp_script_path";

		bash -s -n < "$temp_script_path" &> /dev/null || {
			rm -f "$temp_script_path";
			1>&2 echo "Error in file '$filepath' on line $current_line_number.";
			exit 1;
		};
		bash -s < "$temp_script_path" > "$output_file";
		rm -f "$temp_script_path";

		while IFS="" read -r word || [ -n "$word" ]; do
			parsed_word="$(
				# subshell for safety.
				eval "output=$word";
				# shellcheck disable=SC2154
				printf %s "$output";
			)";
			toplevel_commands+=("$parsed_word");
		done < "$output_file";

		((current_line_number++));
	done < "$filepath";
	rm -f "$output_file";
	
	toplevel_commands_provided=1;
}
read_toplevel_commands_from_arguments() {
	toplevel_commands=("${arg_script[@]}");
	toplevel_commands_provided=1;
}



begin_root_kernel() {
	print_kernel;
	echo;
	echo "###;;;";

	local toplevel_arg;
	for toplevel_arg in "${toplevel_commands[@]}"; do
		echo @@toplevel_arg;
		dump_bin <<<"$toplevel_arg";
	done;

	for id in "${make_command_fail_ids[@]}"; do
		echo @@make_command_fail_id;
		dump_bin <<<"$id";
	done;

	((opt_p)) && echo @opt_p;
	((opt_i)) && echo @opt_i;
	((opt_fake_su)) && echo @fake_su;

	echo @@rrssh_id;
	tr -dc 0123456789abcdefghijklmnopqrstuvwxyz < /dev/urandom | head -c 10 | dump_bin;
	echo @@rrssh_fork_depth;
	dump_bin <<<"0";
	echo @@rrssh_host_depth;
	dump_bin <<<"0";

	local arg;
	for arg in "${kernel_inner_function_args[@]}"; do
		echo @@kernel_inner_function_arg;
		dump_bin <<<"$arg";
	done;
	
	
	echo @end_of_header;
}

run_root_kernel_mode() {
	local mode=$1;

	local temp_kernel_path;
	temp_kernel_path=$(mktemp);
	(

		begin_root_kernel;
		echo @eof;

	) > "$temp_kernel_path";
	local temp_com_file;
	temp_com_file=$(mktemp);
	local rootkernel_stdin;
	rootkernel_stdin=$(mktemp_fifo);
	local rootkernel_stdout;
	rootkernel_stdout=$(mktemp_fifo);
	(
		trap_cmd() {
			# shellcheck disable=SC2317
			echo @panic > "$rootkernel_stdin";
			# shellcheck disable=SC2317
			echo @panic > "$rootkernel_stdin";
			# shellcheck disable=SC2317
			echo @panic > "$rootkernel_stdin";
			# shellcheck disable=SC2317
			echo @panic > "$rootkernel_stdin";
		}
		# trap "trap_cmd;" SIGTERM SIGKILL SIGINT SIGQUIT;

		bash "$temp_kernel_path" -- --mode "$mode" --root --stdin 2> /dev/null;
	) 0< "$rootkernel_stdin" 1> "$rootkernel_stdout" &
	exec 6> "$rootkernel_stdin" 7< "$rootkernel_stdout";
	
	(
		# TODO: improve traps.

		must_panic=0;

		first_loop=1;
		restart_loop=0;
		trap_ran=0;

		trap_cmd() {
			# shellcheck disable=SC2317
			trap_ran=1;
			# shellcheck disable=SC2317
			local i;
			# ensure that we send @panic even if we desync with the
			# messages and dont catch any future @epoll_panic.
			# shellcheck disable=SC2317
			for ((i = 0; i < 10; i++)); do
			# shellcheck disable=SC2317
				echo @panic;
			done 1>&6;
			# shellcheck disable=SC2317
			must_panic=1;
			# shellcheck disable=SC2317
			1>&2 echo;
			# shellcheck disable=SC2317
			1>&2 echo "Triggering panic at earliest opportunity.";
			# shellcheck disable=SC2317
			1>&2 echo;
		}

		# trap "trap_cmd;" SIGTERM SIGKILL SIGINT SIGQUIT;
		trap "echo TERM; trap_cmd;" SIGTERM;
		trap "echo INT; trap_cmd;" SIGINT;
		trap "echo QUIT; trap_cmd;" SIGQUiT;



		while ((first_loop)) || ((restart_loop)); do
			first_loop=0;
			restart_loop=0;
			while IFS="" read -r line || [ -n "$line" ]; do
				case "$line" in
					(@@print_stdout)
						read_bin;
						;;
					(@@print_stderr)
						read_bin 1>&2;
						;;
					(@bliss)
						if ! ((must_panic)); then
							echo @bliss >> "$temp_com_file";
						else
							echo @panic >> "$temp_com_file";
						fi;
						;;
					(@@exitcode)
						echo @@exitcode >> "$temp_com_file";
						read_bin_pipe_dump_bin 2> /dev/null >> "$temp_com_file";
						;;
					(@panic)
						echo @panic >> "$temp_com_file";
						;;
					(@epoll_panic)
						if ! ((must_panic)); then
							echo @continue 1>&6;
						else
							echo @panic 1>&6;
						fi;
						;;
					(@kernel_start)
						true; # we do nothing
						;;
					(@@child_dropdir)
						read_bin_pipe_dump_bin &> /dev/null;
						;;
					(@@coverage)
						if [ -n "$RRSSH_COVERAGE_FILE" ]; then
							read_bin >> "$RRSSH_COVERAGE_FILE";
						else
							read_bin_pipe_dump_bin &> /dev/null;
						fi;
						;;
					(*)
						1>&2 echo "Unknown object in kernel output, will trigger panic: $line";
						must_panic=1;
						;;
				esac;
			done;
			if ((trap_ran)); then
				trap_ran=0;
				restart_loop=1;
			fi;
		done;
	) 0< "$rootkernel_stdout" 7<&-;
	exec 6>&- 7<&-;
	rm -f "$temp_kernel_path";
	rm -f "$rootkernel_stdin";
	rm -f "$rootkernel_stdout";

	local exitcode_received=0;
	local exitcode=0;
	local panic_received=0;
	local bliss_received=0;
	while IFS="" read -r line || [ -n "$line" ]; do
		case "$line" in
			(@@exitcode)
				exitcode_received=1;
				exitcode=$(read_bin);
				# read_line;
				;;
			(@bliss)
				bliss_received=1;
				;;
			(@panic)
				panic_received=1;
				;;
		esac;
	done < "$temp_com_file";
	rm -f "$temp_com_file";

	if ((panic_received)); then
		if ((exitcode_received)); then
			return "$exitcode";
		else
			return 1;
		fi;
	fi;

	if [ "$mode" == kernel-inner-function ] && ((exitcode_received)); then
		return "$exitcode";
	fi;

	if ! ((bliss_received)); then
		1>&2 echo "PROBLEM: The root subkernel did not end blissfully";
		return 1;
	fi;
}

command_check() {
	((toplevel_commands_provided)) || {
		1>&2 echo "You must provide a rrssh script.";
		return 1;
	};

	run_root_kernel_mode scan;
}

command_run() {
	command_check || return 1;

	run_root_kernel_mode run;
}

command_kernel_inner_function() {
	kernel_inner_function_args=("$@");
	run_root_kernel_mode kernel-inner-function;
}

main() {
	if (($# == 0)); then
		echo "You must provide a command.";
		return 1;
	fi;
	local cmd=$1;

	if ((opt_file)); then
		local temp_script_file_path;
		temp_script_file_path=$(mktemp);
		if [ "$arg_file" == "-" ]; then
		    cat > "$temp_script_file_path";
		else
			cat -- "$arg_file" > "$temp_script_file_path";
		fi;
		read_toplevel_commands_from_file "$temp_script_file_path";
		rm -f "$temp_script_file_path";
	elif ((opt_script_provided)); then
		read_toplevel_commands_from_arguments;
	fi

	shift;
	case "$cmd" in
		(print-kernel)
			print_kernel;
			;;
		(run)
			command_run;
			;;
		(check)
			command_check;
			;;
		(kernel-inner-function)
			command_kernel_inner_function "$@";
			;;
		(print)
			((toplevel_commands_provided)) || {
				1>&2 echo "You need to provide a script";
				return 1;
			};
			if ((opt_t)); then
				echo "${#toplevel_commands[@]}";
			else
				local printf_arg='%q\n';
				((opt_l)) && printf_arg='%s\n';
				if ((opt_n)); then
					((arg_n < ${#toplevel_commands[@]})) || {
						1>&2 echo "The value provided to -n is larger than the number of tokens.";
						return 1;
					};
					# shellcheck disable=SC2059
					printf "$printf_arg" "${toplevel_commands[$arg_n]}";
				else
					# shellcheck disable=SC2059
					printf "$printf_arg" "${toplevel_commands[@]}";
				fi;
			fi;
			;;
		(*)
			1>&2 echo "Unknown command '$cmd'.";
			return 1;
			;;
	esac;
}


main "$@";
exit "$?";

